/**
 * Testing utilities and helpers for LightNap Angular application
 *
 * This module exports all testing utilities including:
 * - Mock services (application state and features)
 * - Test data builders/factories
 * - Custom matchers
 * - Shared testing module
 *
 * DEPRECATION NOTE:
 * HTTP API mocks for LightNapWebApiService are now generated by Orval at:
 * @core/backend-api/services/lightnap-api.ts
 *
 * Previously available mock services (mock-identity-data.service, mock-profile.service)
 * have been removed in favor of Orval-generated mocks with realistic Faker.js data.
 * Use Orval mock handlers (getGetProfileMockHandler, etc.) in your tests instead.
 */

export * from './mocks';
export * from './builders';
export * from './helpers';
export * from './test.module';
export * from './test-helpers';

