/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */
import { HttpClient } from "@angular/common/http";
import type { HttpContext, HttpEvent, HttpHeaders, HttpParams, HttpResponse as AngularHttpResponse } from "@angular/common/http";

import { Injectable, inject } from "@angular/core";

import { Observable } from "rxjs";

import type {
  AddUserClaimBodyOne,
  AddUserClaimBodyThree,
  AddUserClaimBodyTwo,
  AdminExternalLoginDtoPagedResponseDto,
  AdminSearchUsersRequestDto,
  AdminUpdateUserRequestDto,
  AdminUserDto,
  ChangeEmailRequestDto,
  ChangePasswordRequestDto,
  ClaimDtoPagedResponseDto,
  CompleteExternalLoginBodyOne,
  CompleteExternalLoginBodyThree,
  CompleteExternalLoginBodyTwo,
  ConfirmEmailChangeRequestDto,
  CreateStaticContentDto,
  CreateStaticContentLanguageDto,
  DeviceDto,
  ExternalLoginRegisterRequestDto,
  ExternalLoginSuccessDto,
  GetMyExternalLogins200OneItem,
  GetMyExternalLogins200ThreeItem,
  GetMyExternalLogins200TwoItem,
  GetMyUserClaimsBodyOne,
  GetMyUserClaimsBodyThree,
  GetMyUserClaimsBodyTwo,
  GetUser200One,
  GetUser200Three,
  GetUser200Two,
  GetUserByUserName200One,
  GetUserByUserName200Three,
  GetUserByUserName200Two,
  GetUsersByIds200OneItem,
  GetUsersByIds200ThreeItem,
  GetUsersByIds200TwoItem,
  LoginRequestDto,
  LoginSuccessDto,
  NewPasswordRequestDto,
  NotificationSearchResultsDto,
  ProfileDto,
  PublicUserDtoPagedResponseDto,
  PublishedStaticContentResultDto,
  RegisterRequestDto,
  RemoveUserClaimBodyOne,
  RemoveUserClaimBodyThree,
  RemoveUserClaimBodyTwo,
  ResetPasswordRequestDto,
  RoleDto,
  SearchClaimRequestDto,
  SearchClaimsBodyOne,
  SearchClaimsBodyThree,
  SearchClaimsBodyTwo,
  SearchExternalLoginsRequestDto,
  SearchNotificationsRequestDto,
  SearchStaticContentRequestDto,
  SearchUserClaimsRequestDto,
  SendMagicLinkRequestDto,
  SendVerificationEmailRequestDto,
  SetUserSettingRequestDto,
  StaticContentDto,
  StaticContentDtoPagedResponseDto,
  StaticContentLanguageDto,
  StaticContentSupportedLanguageDto,
  StringPagedResponseDto,
  SupportedExternalLoginDto,
  UpdateProfileRequestDto,
  UpdateStaticContentBodyOne,
  UpdateStaticContentBodyThree,
  UpdateStaticContentBodyTwo,
  UpdateStaticContentLanguageBodyOne,
  UpdateStaticContentLanguageBodyThree,
  UpdateStaticContentLanguageBodyTwo,
  UserClaimDtoPagedResponseDto,
  UserSettingDto,
  VerifyCodeRequestDto,
  VerifyEmailRequestDto,
} from "../models";

interface HttpClientOptions {
  headers?: HttpHeaders | Record<string, string | string[]>;
  context?: HttpContext;
  params?: HttpParams | Record<string, string | number | boolean | ReadonlyArray<string | number | boolean>>;
  reportProgress?: boolean;
  withCredentials?: boolean;
  credentials?: RequestCredentials;
  keepalive?: boolean;
  priority?: RequestPriority;
  cache?: RequestCache;
  mode?: RequestMode;
  redirect?: RequestRedirect;
  referrer?: string;
  integrity?: string;
  transferCache?: { includeHeaders?: string[] } | boolean;
  timeout?: number;
}

@Injectable({ providedIn: "root" })
export class LightNapWebApiService {
  private readonly http = inject(HttpClient);
  /**
   * @summary Retrieves published static content by key and language code.
   */
  getPublishedStaticContent<TData = PublishedStaticContentResultDto>(
    key: string,
    languageCode: string,
    options?: HttpClientOptions & { observe?: "body" }
  ): Observable<TData>;
  getPublishedStaticContent<TData = PublishedStaticContentResultDto>(
    key: string,
    languageCode: string,
    options?: HttpClientOptions & { observe: "events" }
  ): Observable<HttpEvent<TData>>;
  getPublishedStaticContent<TData = PublishedStaticContentResultDto>(
    key: string,
    languageCode: string,
    options?: HttpClientOptions & { observe: "response" }
  ): Observable<AngularHttpResponse<TData>>;
  getPublishedStaticContent<TData = PublishedStaticContentResultDto>(
    key: string,
    languageCode: string,
    options?: HttpClientOptions & { observe?: any }
  ): Observable<any> {
    return this.http.get<TData>(`/api/Content/published/${key}/${languageCode}`, options);
  }

  /**
   * @summary Retrieves the list of supported languages for static content.
   */
  getSupportedLanguages<TData = StaticContentSupportedLanguageDto[] | null>(options?: HttpClientOptions & { observe?: "body" }): Observable<TData>;
  getSupportedLanguages<TData = StaticContentSupportedLanguageDto[] | null>(
    options?: HttpClientOptions & { observe: "events" }
  ): Observable<HttpEvent<TData>>;
  getSupportedLanguages<TData = StaticContentSupportedLanguageDto[] | null>(
    options?: HttpClientOptions & { observe: "response" }
  ): Observable<AngularHttpResponse<TData>>;
  getSupportedLanguages<TData = StaticContentSupportedLanguageDto[] | null>(options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.get<TData>(`/api/Content/supported-languages`, options);
  }

  /**
   * Requires Administrator or ContentEditor role.
   * @summary Creates a new static content resource.
   */
  createStaticContent<TData = StaticContentDto>(
    createStaticContentDto: CreateStaticContentDto,
    options?: HttpClientOptions & { observe?: "body" }
  ): Observable<TData>;
  createStaticContent<TData = StaticContentDto>(
    createStaticContentDto: CreateStaticContentDto,
    options?: HttpClientOptions & { observe: "events" }
  ): Observable<HttpEvent<TData>>;
  createStaticContent<TData = StaticContentDto>(
    createStaticContentDto: CreateStaticContentDto,
    options?: HttpClientOptions & { observe: "response" }
  ): Observable<AngularHttpResponse<TData>>;
  createStaticContent<TData = StaticContentDto>(
    createStaticContentDto: CreateStaticContentDto,
    options?: HttpClientOptions & { observe?: any }
  ): Observable<any> {
    return this.http.post<TData>(`/api/Content`, createStaticContentDto, options);
  }

  /**
   * @summary Retrieves static content by its key.
   */
  getStaticContent<TData = StaticContentDto>(key: string, options?: HttpClientOptions & { observe?: "body" }): Observable<TData>;
  getStaticContent<TData = StaticContentDto>(key: string, options?: HttpClientOptions & { observe: "events" }): Observable<HttpEvent<TData>>;
  getStaticContent<TData = StaticContentDto>(
    key: string,
    options?: HttpClientOptions & { observe: "response" }
  ): Observable<AngularHttpResponse<TData>>;
  getStaticContent<TData = StaticContentDto>(key: string, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.get<TData>(`/api/Content/${key}`, options);
  }

  /**
   * @summary Updates an existing static content resource.
   */
  updateStaticContent<TData = StaticContentDto>(
    key: string,
    updateStaticContentBody: UpdateStaticContentBodyOne | UpdateStaticContentBodyTwo | UpdateStaticContentBodyThree,
    options?: HttpClientOptions & { observe?: "body" }
  ): Observable<TData>;
  updateStaticContent<TData = StaticContentDto>(
    key: string,
    updateStaticContentBody: UpdateStaticContentBodyOne | UpdateStaticContentBodyTwo | UpdateStaticContentBodyThree,
    options?: HttpClientOptions & { observe: "events" }
  ): Observable<HttpEvent<TData>>;
  updateStaticContent<TData = StaticContentDto>(
    key: string,
    updateStaticContentBody: UpdateStaticContentBodyOne | UpdateStaticContentBodyTwo | UpdateStaticContentBodyThree,
    options?: HttpClientOptions & { observe: "response" }
  ): Observable<AngularHttpResponse<TData>>;
  updateStaticContent<TData = StaticContentDto>(
    key: string,
    updateStaticContentBody: UpdateStaticContentBodyOne | UpdateStaticContentBodyTwo | UpdateStaticContentBodyThree,
    options?: HttpClientOptions & { observe?: any }
  ): Observable<any> {
    return this.http.put<TData>(`/api/Content/${key}`, updateStaticContentBody, options);
  }

  /**
   * Requires Administrator role.
   * @summary Deletes a static content resource by its key.
   */
  deleteStaticContent<TData = boolean>(key: string, options?: HttpClientOptions & { observe?: "body" }): Observable<TData>;
  deleteStaticContent<TData = boolean>(key: string, options?: HttpClientOptions & { observe: "events" }): Observable<HttpEvent<TData>>;
  deleteStaticContent<TData = boolean>(key: string, options?: HttpClientOptions & { observe: "response" }): Observable<AngularHttpResponse<TData>>;
  deleteStaticContent<TData = boolean>(key: string, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.delete<TData>(`/api/Content/${key}`, options);
  }

  /**
   * Requires Administrator or ContentEditor role.
   * @summary Searches for static content based on the provided criteria.
   */
  searchStaticContent<TData = StaticContentDtoPagedResponseDto>(
    searchStaticContentRequestDto: SearchStaticContentRequestDto,
    options?: HttpClientOptions & { observe?: "body" }
  ): Observable<TData>;
  searchStaticContent<TData = StaticContentDtoPagedResponseDto>(
    searchStaticContentRequestDto: SearchStaticContentRequestDto,
    options?: HttpClientOptions & { observe: "events" }
  ): Observable<HttpEvent<TData>>;
  searchStaticContent<TData = StaticContentDtoPagedResponseDto>(
    searchStaticContentRequestDto: SearchStaticContentRequestDto,
    options?: HttpClientOptions & { observe: "response" }
  ): Observable<AngularHttpResponse<TData>>;
  searchStaticContent<TData = StaticContentDtoPagedResponseDto>(
    searchStaticContentRequestDto: SearchStaticContentRequestDto,
    options?: HttpClientOptions & { observe?: any }
  ): Observable<any> {
    return this.http.post<TData>(`/api/Content/search`, searchStaticContentRequestDto, options);
  }

  /**
   * @summary Retrieves a specific language version of static content.
   */
  getStaticContentLanguage<TData = StaticContentLanguageDto>(
    key: string,
    languageCode: string,
    options?: HttpClientOptions & { observe?: "body" }
  ): Observable<TData>;
  getStaticContentLanguage<TData = StaticContentLanguageDto>(
    key: string,
    languageCode: string,
    options?: HttpClientOptions & { observe: "events" }
  ): Observable<HttpEvent<TData>>;
  getStaticContentLanguage<TData = StaticContentLanguageDto>(
    key: string,
    languageCode: string,
    options?: HttpClientOptions & { observe: "response" }
  ): Observable<AngularHttpResponse<TData>>;
  getStaticContentLanguage<TData = StaticContentLanguageDto>(
    key: string,
    languageCode: string,
    options?: HttpClientOptions & { observe?: any }
  ): Observable<any> {
    return this.http.get<TData>(`/api/Content/${key}/languages/${languageCode}`, options);
  }

  /**
   * @summary Creates a new language version for an existing static content resource.
   */
  createStaticContentLanguage<TData = StaticContentLanguageDto>(
    key: string,
    languageCode: string,
    createStaticContentLanguageDto: CreateStaticContentLanguageDto,
    options?: HttpClientOptions & { observe?: "body" }
  ): Observable<TData>;
  createStaticContentLanguage<TData = StaticContentLanguageDto>(
    key: string,
    languageCode: string,
    createStaticContentLanguageDto: CreateStaticContentLanguageDto,
    options?: HttpClientOptions & { observe: "events" }
  ): Observable<HttpEvent<TData>>;
  createStaticContentLanguage<TData = StaticContentLanguageDto>(
    key: string,
    languageCode: string,
    createStaticContentLanguageDto: CreateStaticContentLanguageDto,
    options?: HttpClientOptions & { observe: "response" }
  ): Observable<AngularHttpResponse<TData>>;
  createStaticContentLanguage<TData = StaticContentLanguageDto>(
    key: string,
    languageCode: string,
    createStaticContentLanguageDto: CreateStaticContentLanguageDto,
    options?: HttpClientOptions & { observe?: any }
  ): Observable<any> {
    return this.http.post<TData>(`/api/Content/${key}/languages/${languageCode}`, createStaticContentLanguageDto, options);
  }

  /**
   * @summary Updates a language version of static content.
   */
  updateStaticContentLanguage<TData = StaticContentLanguageDto>(
    key: string,
    languageCode: string,
    updateStaticContentLanguageBody: UpdateStaticContentLanguageBodyOne | UpdateStaticContentLanguageBodyTwo | UpdateStaticContentLanguageBodyThree,
    options?: HttpClientOptions & { observe?: "body" }
  ): Observable<TData>;
  updateStaticContentLanguage<TData = StaticContentLanguageDto>(
    key: string,
    languageCode: string,
    updateStaticContentLanguageBody: UpdateStaticContentLanguageBodyOne | UpdateStaticContentLanguageBodyTwo | UpdateStaticContentLanguageBodyThree,
    options?: HttpClientOptions & { observe: "events" }
  ): Observable<HttpEvent<TData>>;
  updateStaticContentLanguage<TData = StaticContentLanguageDto>(
    key: string,
    languageCode: string,
    updateStaticContentLanguageBody: UpdateStaticContentLanguageBodyOne | UpdateStaticContentLanguageBodyTwo | UpdateStaticContentLanguageBodyThree,
    options?: HttpClientOptions & { observe: "response" }
  ): Observable<AngularHttpResponse<TData>>;
  updateStaticContentLanguage<TData = StaticContentLanguageDto>(
    key: string,
    languageCode: string,
    updateStaticContentLanguageBody: UpdateStaticContentLanguageBodyOne | UpdateStaticContentLanguageBodyTwo | UpdateStaticContentLanguageBodyThree,
    options?: HttpClientOptions & { observe?: any }
  ): Observable<any> {
    return this.http.put<TData>(`/api/Content/${key}/languages/${languageCode}`, updateStaticContentLanguageBody, options);
  }

  /**
   * Requires Administrator role.
   * @summary Deletes a language version of static content.
   */
  deleteStaticContentLanguage<TData = boolean>(
    key: string,
    languageCode: string,
    options?: HttpClientOptions & { observe?: "body" }
  ): Observable<TData>;
  deleteStaticContentLanguage<TData = boolean>(
    key: string,
    languageCode: string,
    options?: HttpClientOptions & { observe: "events" }
  ): Observable<HttpEvent<TData>>;
  deleteStaticContentLanguage<TData = boolean>(
    key: string,
    languageCode: string,
    options?: HttpClientOptions & { observe: "response" }
  ): Observable<AngularHttpResponse<TData>>;
  deleteStaticContentLanguage<TData = boolean>(key: string, languageCode: string, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.delete<TData>(`/api/Content/${key}/languages/${languageCode}`, options);
  }

  /**
   * @summary Retrieves all language versions of a static content resource.
   */
  getStaticContentLanguages<TData = StaticContentLanguageDto[] | null>(
    key: string,
    options?: HttpClientOptions & { observe?: "body" }
  ): Observable<TData>;
  getStaticContentLanguages<TData = StaticContentLanguageDto[] | null>(
    key: string,
    options?: HttpClientOptions & { observe: "events" }
  ): Observable<HttpEvent<TData>>;
  getStaticContentLanguages<TData = StaticContentLanguageDto[] | null>(
    key: string,
    options?: HttpClientOptions & { observe: "response" }
  ): Observable<AngularHttpResponse<TData>>;
  getStaticContentLanguages<TData = StaticContentLanguageDto[] | null>(
    key: string,
    options?: HttpClientOptions & { observe?: any }
  ): Observable<any> {
    return this.http.get<TData>(`/api/Content/${key}/languages`, options);
  }

  /**
   * @summary Gets the supported external login providers based on the application's configuration.
   */
  getSupportedExternalLogins<TData = SupportedExternalLoginDto[] | null>(options?: HttpClientOptions & { observe?: "body" }): Observable<TData>;
  getSupportedExternalLogins<TData = SupportedExternalLoginDto[] | null>(
    options?: HttpClientOptions & { observe: "events" }
  ): Observable<HttpEvent<TData>>;
  getSupportedExternalLogins<TData = SupportedExternalLoginDto[] | null>(
    options?: HttpClientOptions & { observe: "response" }
  ): Observable<AngularHttpResponse<TData>>;
  getSupportedExternalLogins<TData = SupportedExternalLoginDto[] | null>(options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.get<TData>(`/api/ExternalLogin/supported`, options);
  }

  /**
   * @summary Gets the supported external login providers based on the application's configuration.
   */
  searchExternalLogins<TData = AdminExternalLoginDtoPagedResponseDto>(
    searchExternalLoginsRequestDto: SearchExternalLoginsRequestDto,
    options?: HttpClientOptions & { observe?: "body" }
  ): Observable<TData>;
  searchExternalLogins<TData = AdminExternalLoginDtoPagedResponseDto>(
    searchExternalLoginsRequestDto: SearchExternalLoginsRequestDto,
    options?: HttpClientOptions & { observe: "events" }
  ): Observable<HttpEvent<TData>>;
  searchExternalLogins<TData = AdminExternalLoginDtoPagedResponseDto>(
    searchExternalLoginsRequestDto: SearchExternalLoginsRequestDto,
    options?: HttpClientOptions & { observe: "response" }
  ): Observable<AngularHttpResponse<TData>>;
  searchExternalLogins<TData = AdminExternalLoginDtoPagedResponseDto>(
    searchExternalLoginsRequestDto: SearchExternalLoginsRequestDto,
    options?: HttpClientOptions & { observe?: any }
  ): Observable<any> {
    return this.http.post<TData>(`/api/ExternalLogin/search`, searchExternalLoginsRequestDto, options);
  }

  /**
 * This operation requires administrator privileges. Removing an external login may
            affect the user's ability to sign in using that provider.
 * @summary Removes an external login association from the specified user account.
 */
  removeExternalLogin<TData = boolean>(
    userId: string,
    loginProvider: string,
    providerKey: string,
    options?: HttpClientOptions & { observe?: "body" }
  ): Observable<TData>;
  removeExternalLogin<TData = boolean>(
    userId: string,
    loginProvider: string,
    providerKey: string,
    options?: HttpClientOptions & { observe: "events" }
  ): Observable<HttpEvent<TData>>;
  removeExternalLogin<TData = boolean>(
    userId: string,
    loginProvider: string,
    providerKey: string,
    options?: HttpClientOptions & { observe: "response" }
  ): Observable<AngularHttpResponse<TData>>;
  removeExternalLogin<TData = boolean>(
    userId: string,
    loginProvider: string,
    providerKey: string,
    options?: HttpClientOptions & { observe?: any }
  ): Observable<any> {
    return this.http.delete<TData>(`/api/ExternalLogin/remove/${userId}/${loginProvider}/${providerKey}`, options);
  }

  /**
   * @summary Confirms external login association with current user.
   */
  getExternalLoginResult<TData = ExternalLoginSuccessDto>(
    confirmationToken: string,
    options?: HttpClientOptions & { observe?: "body" }
  ): Observable<TData>;
  getExternalLoginResult<TData = ExternalLoginSuccessDto>(
    confirmationToken: string,
    options?: HttpClientOptions & { observe: "events" }
  ): Observable<HttpEvent<TData>>;
  getExternalLoginResult<TData = ExternalLoginSuccessDto>(
    confirmationToken: string,
    options?: HttpClientOptions & { observe: "response" }
  ): Observable<AngularHttpResponse<TData>>;
  getExternalLoginResult<TData = ExternalLoginSuccessDto>(
    confirmationToken: string,
    options?: HttpClientOptions & { observe?: any }
  ): Observable<any> {
    return this.http.get<TData>(`/api/ExternalLogin/result/${confirmationToken}`, options);
  }

  /**
   * @summary Completes the external login when the account is already linked.
   */
  completeExternalLogin<TData = LoginSuccessDto>(
    confirmationToken: string,
    completeExternalLoginBody: CompleteExternalLoginBodyOne | CompleteExternalLoginBodyTwo | CompleteExternalLoginBodyThree,
    options?: HttpClientOptions & { observe?: "body" }
  ): Observable<TData>;
  completeExternalLogin<TData = LoginSuccessDto>(
    confirmationToken: string,
    completeExternalLoginBody: CompleteExternalLoginBodyOne | CompleteExternalLoginBodyTwo | CompleteExternalLoginBodyThree,
    options?: HttpClientOptions & { observe: "events" }
  ): Observable<HttpEvent<TData>>;
  completeExternalLogin<TData = LoginSuccessDto>(
    confirmationToken: string,
    completeExternalLoginBody: CompleteExternalLoginBodyOne | CompleteExternalLoginBodyTwo | CompleteExternalLoginBodyThree,
    options?: HttpClientOptions & { observe: "response" }
  ): Observable<AngularHttpResponse<TData>>;
  completeExternalLogin<TData = LoginSuccessDto>(
    confirmationToken: string,
    completeExternalLoginBody: CompleteExternalLoginBodyOne | CompleteExternalLoginBodyTwo | CompleteExternalLoginBodyThree,
    options?: HttpClientOptions & { observe?: any }
  ): Observable<any> {
    return this.http.post<TData>(`/api/ExternalLogin/complete/${confirmationToken}`, completeExternalLoginBody, options);
  }

  /**
   * @summary Completes the external login registration when the user is not logged in yet.
   */
  completeExternalLoginRegistration<TData = LoginSuccessDto>(
    confirmationToken: string,
    externalLoginRegisterRequestDto: ExternalLoginRegisterRequestDto,
    options?: HttpClientOptions & { observe?: "body" }
  ): Observable<TData>;
  completeExternalLoginRegistration<TData = LoginSuccessDto>(
    confirmationToken: string,
    externalLoginRegisterRequestDto: ExternalLoginRegisterRequestDto,
    options?: HttpClientOptions & { observe: "events" }
  ): Observable<HttpEvent<TData>>;
  completeExternalLoginRegistration<TData = LoginSuccessDto>(
    confirmationToken: string,
    externalLoginRegisterRequestDto: ExternalLoginRegisterRequestDto,
    options?: HttpClientOptions & { observe: "response" }
  ): Observable<AngularHttpResponse<TData>>;
  completeExternalLoginRegistration<TData = LoginSuccessDto>(
    confirmationToken: string,
    externalLoginRegisterRequestDto: ExternalLoginRegisterRequestDto,
    options?: HttpClientOptions & { observe?: any }
  ): Observable<any> {
    return this.http.post<TData>(`/api/ExternalLogin/register/${confirmationToken}`, externalLoginRegisterRequestDto, options);
  }

  /**
   * @summary Logs in a user.
   */
  logIn<TData = LoginSuccessDto>(loginRequestDto: LoginRequestDto, options?: HttpClientOptions & { observe?: "body" }): Observable<TData>;
  logIn<TData = LoginSuccessDto>(loginRequestDto: LoginRequestDto, options?: HttpClientOptions & { observe: "events" }): Observable<HttpEvent<TData>>;
  logIn<TData = LoginSuccessDto>(
    loginRequestDto: LoginRequestDto,
    options?: HttpClientOptions & { observe: "response" }
  ): Observable<AngularHttpResponse<TData>>;
  logIn<TData = LoginSuccessDto>(loginRequestDto: LoginRequestDto, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.post<TData>(`/api/Identity/login`, loginRequestDto, options);
  }

  /**
   * @summary Registers a new user.
   */
  register<TData = LoginSuccessDto>(registerRequestDto: RegisterRequestDto, options?: HttpClientOptions & { observe?: "body" }): Observable<TData>;
  register<TData = LoginSuccessDto>(
    registerRequestDto: RegisterRequestDto,
    options?: HttpClientOptions & { observe: "events" }
  ): Observable<HttpEvent<TData>>;
  register<TData = LoginSuccessDto>(
    registerRequestDto: RegisterRequestDto,
    options?: HttpClientOptions & { observe: "response" }
  ): Observable<AngularHttpResponse<TData>>;
  register<TData = LoginSuccessDto>(registerRequestDto: RegisterRequestDto, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.post<TData>(`/api/Identity/register`, registerRequestDto, options);
  }

  /**
   * @summary Logs out the current user.
   */
  logOut<TData = boolean>(options?: HttpClientOptions & { observe?: "body" }): Observable<TData>;
  logOut<TData = boolean>(options?: HttpClientOptions & { observe: "events" }): Observable<HttpEvent<TData>>;
  logOut<TData = boolean>(options?: HttpClientOptions & { observe: "response" }): Observable<AngularHttpResponse<TData>>;
  logOut<TData = boolean>(options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.get<TData>(`/api/Identity/logout`, options);
  }

  /**
   * @summary Changes the password of the current user.
   */
  changePassword<TData = boolean>(
    changePasswordRequestDto: ChangePasswordRequestDto,
    options?: HttpClientOptions & { observe?: "body" }
  ): Observable<TData>;
  changePassword<TData = boolean>(
    changePasswordRequestDto: ChangePasswordRequestDto,
    options?: HttpClientOptions & { observe: "events" }
  ): Observable<HttpEvent<TData>>;
  changePassword<TData = boolean>(
    changePasswordRequestDto: ChangePasswordRequestDto,
    options?: HttpClientOptions & { observe: "response" }
  ): Observable<AngularHttpResponse<TData>>;
  changePassword<TData = boolean>(
    changePasswordRequestDto: ChangePasswordRequestDto,
    options?: HttpClientOptions & { observe?: any }
  ): Observable<any> {
    return this.http.post<TData>(`/api/Identity/change-password`, changePasswordRequestDto, options);
  }

  /**
   * @summary Changes the email of the current user.
   */
  changeEmail<TData = boolean>(changeEmailRequestDto: ChangeEmailRequestDto, options?: HttpClientOptions & { observe?: "body" }): Observable<TData>;
  changeEmail<TData = boolean>(
    changeEmailRequestDto: ChangeEmailRequestDto,
    options?: HttpClientOptions & { observe: "events" }
  ): Observable<HttpEvent<TData>>;
  changeEmail<TData = boolean>(
    changeEmailRequestDto: ChangeEmailRequestDto,
    options?: HttpClientOptions & { observe: "response" }
  ): Observable<AngularHttpResponse<TData>>;
  changeEmail<TData = boolean>(changeEmailRequestDto: ChangeEmailRequestDto, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.post<TData>(`/api/Identity/change-email`, changeEmailRequestDto, options);
  }

  /**
   * @summary Confirms the email change of the current user.
   */
  confirmEmailChange<TData = boolean>(
    confirmEmailChangeRequestDto: ConfirmEmailChangeRequestDto,
    options?: HttpClientOptions & { observe?: "body" }
  ): Observable<TData>;
  confirmEmailChange<TData = boolean>(
    confirmEmailChangeRequestDto: ConfirmEmailChangeRequestDto,
    options?: HttpClientOptions & { observe: "events" }
  ): Observable<HttpEvent<TData>>;
  confirmEmailChange<TData = boolean>(
    confirmEmailChangeRequestDto: ConfirmEmailChangeRequestDto,
    options?: HttpClientOptions & { observe: "response" }
  ): Observable<AngularHttpResponse<TData>>;
  confirmEmailChange<TData = boolean>(
    confirmEmailChangeRequestDto: ConfirmEmailChangeRequestDto,
    options?: HttpClientOptions & { observe?: any }
  ): Observable<any> {
    return this.http.post<TData>(`/api/Identity/confirm-email-change`, confirmEmailChangeRequestDto, options);
  }

  /**
   * @summary Resets the password for a user.
   */
  resetPassword<TData = boolean>(
    resetPasswordRequestDto: ResetPasswordRequestDto,
    options?: HttpClientOptions & { observe?: "body" }
  ): Observable<TData>;
  resetPassword<TData = boolean>(
    resetPasswordRequestDto: ResetPasswordRequestDto,
    options?: HttpClientOptions & { observe: "events" }
  ): Observable<HttpEvent<TData>>;
  resetPassword<TData = boolean>(
    resetPasswordRequestDto: ResetPasswordRequestDto,
    options?: HttpClientOptions & { observe: "response" }
  ): Observable<AngularHttpResponse<TData>>;
  resetPassword<TData = boolean>(resetPasswordRequestDto: ResetPasswordRequestDto, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.post<TData>(`/api/Identity/reset-password`, resetPasswordRequestDto, options);
  }

  /**
   * @summary Sets a new password for a user.
   */
  newPassword<TData = LoginSuccessDto>(
    newPasswordRequestDto: NewPasswordRequestDto,
    options?: HttpClientOptions & { observe?: "body" }
  ): Observable<TData>;
  newPassword<TData = LoginSuccessDto>(
    newPasswordRequestDto: NewPasswordRequestDto,
    options?: HttpClientOptions & { observe: "events" }
  ): Observable<HttpEvent<TData>>;
  newPassword<TData = LoginSuccessDto>(
    newPasswordRequestDto: NewPasswordRequestDto,
    options?: HttpClientOptions & { observe: "response" }
  ): Observable<AngularHttpResponse<TData>>;
  newPassword<TData = LoginSuccessDto>(
    newPasswordRequestDto: NewPasswordRequestDto,
    options?: HttpClientOptions & { observe?: any }
  ): Observable<any> {
    return this.http.post<TData>(`/api/Identity/new-password`, newPasswordRequestDto, options);
  }

  /**
   * @summary Verifies the two-factor authentication code.
   */
  verifyCode<TData = string | null>(
    verifyCodeRequestDto: VerifyCodeRequestDto,
    options?: HttpClientOptions & { observe?: "body" }
  ): Observable<TData>;
  verifyCode<TData = string | null>(
    verifyCodeRequestDto: VerifyCodeRequestDto,
    options?: HttpClientOptions & { observe: "events" }
  ): Observable<HttpEvent<TData>>;
  verifyCode<TData = string | null>(
    verifyCodeRequestDto: VerifyCodeRequestDto,
    options?: HttpClientOptions & { observe: "response" }
  ): Observable<AngularHttpResponse<TData>>;
  verifyCode<TData = string | null>(verifyCodeRequestDto: VerifyCodeRequestDto, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.post<TData>(`/api/Identity/verify-code`, verifyCodeRequestDto, options);
  }

  /**
   * @summary Refreshes the access token using the refresh token.
   */
  getAccessToken<TData = string | null>(options?: HttpClientOptions & { observe?: "body" }): Observable<TData>;
  getAccessToken<TData = string | null>(options?: HttpClientOptions & { observe: "events" }): Observable<HttpEvent<TData>>;
  getAccessToken<TData = string | null>(options?: HttpClientOptions & { observe: "response" }): Observable<AngularHttpResponse<TData>>;
  getAccessToken<TData = string | null>(options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.get<TData>(`/api/Identity/access-token`, options);
  }

  /**
   * @summary Requests an email verification email for a user.
   */
  requestVerificationEmail<TData = boolean>(
    sendVerificationEmailRequestDto: SendVerificationEmailRequestDto,
    options?: HttpClientOptions & { observe?: "body" }
  ): Observable<TData>;
  requestVerificationEmail<TData = boolean>(
    sendVerificationEmailRequestDto: SendVerificationEmailRequestDto,
    options?: HttpClientOptions & { observe: "events" }
  ): Observable<HttpEvent<TData>>;
  requestVerificationEmail<TData = boolean>(
    sendVerificationEmailRequestDto: SendVerificationEmailRequestDto,
    options?: HttpClientOptions & { observe: "response" }
  ): Observable<AngularHttpResponse<TData>>;
  requestVerificationEmail<TData = boolean>(
    sendVerificationEmailRequestDto: SendVerificationEmailRequestDto,
    options?: HttpClientOptions & { observe?: any }
  ): Observable<any> {
    return this.http.post<TData>(`/api/Identity/request-verification-email`, sendVerificationEmailRequestDto, options);
  }

  /**
   * @summary Verifies the email address of a user.
   */
  verifyEmail<TData = boolean>(verifyEmailRequestDto: VerifyEmailRequestDto, options?: HttpClientOptions & { observe?: "body" }): Observable<TData>;
  verifyEmail<TData = boolean>(
    verifyEmailRequestDto: VerifyEmailRequestDto,
    options?: HttpClientOptions & { observe: "events" }
  ): Observable<HttpEvent<TData>>;
  verifyEmail<TData = boolean>(
    verifyEmailRequestDto: VerifyEmailRequestDto,
    options?: HttpClientOptions & { observe: "response" }
  ): Observable<AngularHttpResponse<TData>>;
  verifyEmail<TData = boolean>(verifyEmailRequestDto: VerifyEmailRequestDto, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.post<TData>(`/api/Identity/verify-email`, verifyEmailRequestDto, options);
  }

  /**
   * @summary Requests a magic link the user can use to log in.
   */
  requestMagicLinkEmail<TData = boolean>(
    sendMagicLinkRequestDto: SendMagicLinkRequestDto,
    options?: HttpClientOptions & { observe?: "body" }
  ): Observable<TData>;
  requestMagicLinkEmail<TData = boolean>(
    sendMagicLinkRequestDto: SendMagicLinkRequestDto,
    options?: HttpClientOptions & { observe: "events" }
  ): Observable<HttpEvent<TData>>;
  requestMagicLinkEmail<TData = boolean>(
    sendMagicLinkRequestDto: SendMagicLinkRequestDto,
    options?: HttpClientOptions & { observe: "response" }
  ): Observable<AngularHttpResponse<TData>>;
  requestMagicLinkEmail<TData = boolean>(
    sendMagicLinkRequestDto: SendMagicLinkRequestDto,
    options?: HttpClientOptions & { observe?: any }
  ): Observable<any> {
    return this.http.post<TData>(`/api/Identity/request-magic-link`, sendMagicLinkRequestDto, options);
  }

  /**
   * @summary Retrieves the list of devices.
   */
  getDevices<TData = DeviceDto[] | null>(options?: HttpClientOptions & { observe?: "body" }): Observable<TData>;
  getDevices<TData = DeviceDto[] | null>(options?: HttpClientOptions & { observe: "events" }): Observable<HttpEvent<TData>>;
  getDevices<TData = DeviceDto[] | null>(options?: HttpClientOptions & { observe: "response" }): Observable<AngularHttpResponse<TData>>;
  getDevices<TData = DeviceDto[] | null>(options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.get<TData>(`/api/Identity/devices`, options);
  }

  /**
   * @summary Revokes a device.
   */
  revokeDevice<TData = boolean>(deviceId: string, options?: HttpClientOptions & { observe?: "body" }): Observable<TData>;
  revokeDevice<TData = boolean>(deviceId: string, options?: HttpClientOptions & { observe: "events" }): Observable<HttpEvent<TData>>;
  revokeDevice<TData = boolean>(deviceId: string, options?: HttpClientOptions & { observe: "response" }): Observable<AngularHttpResponse<TData>>;
  revokeDevice<TData = boolean>(deviceId: string, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.delete<TData>(`/api/Identity/devices/${deviceId}`, options);
  }

  /**
   * @summary Retrieves the profile of the current user.
   */
  getProfile<TData = ProfileDto>(options?: HttpClientOptions & { observe?: "body" }): Observable<TData>;
  getProfile<TData = ProfileDto>(options?: HttpClientOptions & { observe: "events" }): Observable<HttpEvent<TData>>;
  getProfile<TData = ProfileDto>(options?: HttpClientOptions & { observe: "response" }): Observable<AngularHttpResponse<TData>>;
  getProfile<TData = ProfileDto>(options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.get<TData>(`/api/users/me/profile`, options);
  }

  /**
   * @summary Updates the profile of the current user.
   */
  updateMyProfile<TData = ProfileDto>(
    updateProfileRequestDto: UpdateProfileRequestDto,
    options?: HttpClientOptions & { observe?: "body" }
  ): Observable<TData>;
  updateMyProfile<TData = ProfileDto>(
    updateProfileRequestDto: UpdateProfileRequestDto,
    options?: HttpClientOptions & { observe: "events" }
  ): Observable<HttpEvent<TData>>;
  updateMyProfile<TData = ProfileDto>(
    updateProfileRequestDto: UpdateProfileRequestDto,
    options?: HttpClientOptions & { observe: "response" }
  ): Observable<AngularHttpResponse<TData>>;
  updateMyProfile<TData = ProfileDto>(
    updateProfileRequestDto: UpdateProfileRequestDto,
    options?: HttpClientOptions & { observe?: any }
  ): Observable<any> {
    return this.http.put<TData>(`/api/users/me/profile`, updateProfileRequestDto, options);
  }

  /**
   * @summary Searches the notifications of the current user.
   */
  searchMyNotifications<TData = NotificationSearchResultsDto>(
    searchNotificationsRequestDto: SearchNotificationsRequestDto,
    options?: HttpClientOptions & { observe?: "body" }
  ): Observable<TData>;
  searchMyNotifications<TData = NotificationSearchResultsDto>(
    searchNotificationsRequestDto: SearchNotificationsRequestDto,
    options?: HttpClientOptions & { observe: "events" }
  ): Observable<HttpEvent<TData>>;
  searchMyNotifications<TData = NotificationSearchResultsDto>(
    searchNotificationsRequestDto: SearchNotificationsRequestDto,
    options?: HttpClientOptions & { observe: "response" }
  ): Observable<AngularHttpResponse<TData>>;
  searchMyNotifications<TData = NotificationSearchResultsDto>(
    searchNotificationsRequestDto: SearchNotificationsRequestDto,
    options?: HttpClientOptions & { observe?: any }
  ): Observable<any> {
    return this.http.post<TData>(`/api/users/me/notifications`, searchNotificationsRequestDto, options);
  }

  /**
   * @summary Marks all notifications as read for the current user.
   */
  markAllMyNotificationsAsRead<TData = boolean>(options?: HttpClientOptions & { observe?: "body" }): Observable<TData>;
  markAllMyNotificationsAsRead<TData = boolean>(options?: HttpClientOptions & { observe: "events" }): Observable<HttpEvent<TData>>;
  markAllMyNotificationsAsRead<TData = boolean>(options?: HttpClientOptions & { observe: "response" }): Observable<AngularHttpResponse<TData>>;
  markAllMyNotificationsAsRead<TData = boolean>(options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.put<TData>(`/api/users/me/notifications/mark-all-as-read`, undefined, options);
  }

  /**
   * @summary Marks a specific notification as read for the current user.
   */
  markMyNotificationAsRead<TData = boolean>(id: number, options?: HttpClientOptions & { observe?: "body" }): Observable<TData>;
  markMyNotificationAsRead<TData = boolean>(id: number, options?: HttpClientOptions & { observe: "events" }): Observable<HttpEvent<TData>>;
  markMyNotificationAsRead<TData = boolean>(
    id: number,
    options?: HttpClientOptions & { observe: "response" }
  ): Observable<AngularHttpResponse<TData>>;
  markMyNotificationAsRead<TData = boolean>(id: number, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.put<TData>(`/api/users/me/notifications/${id}/mark-as-read`, undefined, options);
  }

  /**
 * This method returns a list of claims for the user making the request. The claims
            provide  information about the user's identity, roles, or other attributes. The user must be authenticated
            to access this endpoint.
 * @summary Retrieves the claims associated with the currently authenticated user.
 */
  getMyUserClaims<TData = ClaimDtoPagedResponseDto>(
    getMyUserClaimsBody: GetMyUserClaimsBodyOne | GetMyUserClaimsBodyTwo | GetMyUserClaimsBodyThree,
    options?: HttpClientOptions & { observe?: "body" }
  ): Observable<TData>;
  getMyUserClaims<TData = ClaimDtoPagedResponseDto>(
    getMyUserClaimsBody: GetMyUserClaimsBodyOne | GetMyUserClaimsBodyTwo | GetMyUserClaimsBodyThree,
    options?: HttpClientOptions & { observe: "events" }
  ): Observable<HttpEvent<TData>>;
  getMyUserClaims<TData = ClaimDtoPagedResponseDto>(
    getMyUserClaimsBody: GetMyUserClaimsBodyOne | GetMyUserClaimsBodyTwo | GetMyUserClaimsBodyThree,
    options?: HttpClientOptions & { observe: "response" }
  ): Observable<AngularHttpResponse<TData>>;
  getMyUserClaims<TData = ClaimDtoPagedResponseDto>(
    getMyUserClaimsBody: GetMyUserClaimsBodyOne | GetMyUserClaimsBodyTwo | GetMyUserClaimsBodyThree,
    options?: HttpClientOptions & { observe?: any }
  ): Observable<any> {
    return this.http.get<TData>(`/api/users/me/claims`, options);
  }

  /**
   * @summary Gets the user settings for the current user.
   */
  getMyUserSettings<TData = UserSettingDto[] | null>(options?: HttpClientOptions & { observe?: "body" }): Observable<TData>;
  getMyUserSettings<TData = UserSettingDto[] | null>(options?: HttpClientOptions & { observe: "events" }): Observable<HttpEvent<TData>>;
  getMyUserSettings<TData = UserSettingDto[] | null>(options?: HttpClientOptions & { observe: "response" }): Observable<AngularHttpResponse<TData>>;
  getMyUserSettings<TData = UserSettingDto[] | null>(options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.get<TData>(`/api/users/me/settings`, options);
  }

  /**
 * This method applies the changes to the user's settings and returns the updated
            setting in the response. Ensure that the provided request data is valid and complete before calling this
            method.
 * @summary Updates the user setting based on the provided request data.
 */
  setMyUserSetting<TData = UserSettingDto>(
    setUserSettingRequestDto: SetUserSettingRequestDto,
    options?: HttpClientOptions & { observe?: "body" }
  ): Observable<TData>;
  setMyUserSetting<TData = UserSettingDto>(
    setUserSettingRequestDto: SetUserSettingRequestDto,
    options?: HttpClientOptions & { observe: "events" }
  ): Observable<HttpEvent<TData>>;
  setMyUserSetting<TData = UserSettingDto>(
    setUserSettingRequestDto: SetUserSettingRequestDto,
    options?: HttpClientOptions & { observe: "response" }
  ): Observable<AngularHttpResponse<TData>>;
  setMyUserSetting<TData = UserSettingDto>(
    setUserSettingRequestDto: SetUserSettingRequestDto,
    options?: HttpClientOptions & { observe?: any }
  ): Observable<any> {
    return this.http.patch<TData>(`/api/users/me/settings`, setUserSettingRequestDto, options);
  }

  /**
   * @summary Retrieves all external login providers linked to the current user.
   */
  getMyExternalLogins<
    TData = GetMyExternalLogins200OneItem[] | null | GetMyExternalLogins200TwoItem[] | null | GetMyExternalLogins200ThreeItem[] | null,
  >(options?: HttpClientOptions & { observe?: "body" }): Observable<TData>;
  getMyExternalLogins<
    TData = GetMyExternalLogins200OneItem[] | null | GetMyExternalLogins200TwoItem[] | null | GetMyExternalLogins200ThreeItem[] | null,
  >(options?: HttpClientOptions & { observe: "events" }): Observable<HttpEvent<TData>>;
  getMyExternalLogins<
    TData = GetMyExternalLogins200OneItem[] | null | GetMyExternalLogins200TwoItem[] | null | GetMyExternalLogins200ThreeItem[] | null,
  >(options?: HttpClientOptions & { observe: "response" }): Observable<AngularHttpResponse<TData>>;
  getMyExternalLogins<
    TData = GetMyExternalLogins200OneItem[] | null | GetMyExternalLogins200TwoItem[] | null | GetMyExternalLogins200ThreeItem[] | null,
  >(options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.get<TData>(`/api/users/me/external-logins`, options);
  }

  /**
   * @summary Removes an external login provider from the current user's account.
   */
  removeMyExternalLogin<TData = boolean>(
    loginProvider: string,
    providerKey: string,
    options?: HttpClientOptions & { observe?: "body" }
  ): Observable<TData>;
  removeMyExternalLogin<TData = boolean>(
    loginProvider: string,
    providerKey: string,
    options?: HttpClientOptions & { observe: "events" }
  ): Observable<HttpEvent<TData>>;
  removeMyExternalLogin<TData = boolean>(
    loginProvider: string,
    providerKey: string,
    options?: HttpClientOptions & { observe: "response" }
  ): Observable<AngularHttpResponse<TData>>;
  removeMyExternalLogin<TData = boolean>(
    loginProvider: string,
    providerKey: string,
    options?: HttpClientOptions & { observe?: any }
  ): Observable<any> {
    return this.http.delete<TData>(`/api/users/me/external-logins/${loginProvider}/${providerKey}`, options);
  }

  /**
   * @summary Retrieves a user by ID.
   */
  getUser<TData = GetUser200One | GetUser200Two | GetUser200Three>(
    userId: string,
    options?: HttpClientOptions & { observe?: "body" }
  ): Observable<TData>;
  getUser<TData = GetUser200One | GetUser200Two | GetUser200Three>(
    userId: string,
    options?: HttpClientOptions & { observe: "events" }
  ): Observable<HttpEvent<TData>>;
  getUser<TData = GetUser200One | GetUser200Two | GetUser200Three>(
    userId: string,
    options?: HttpClientOptions & { observe: "response" }
  ): Observable<AngularHttpResponse<TData>>;
  getUser<TData = GetUser200One | GetUser200Two | GetUser200Three>(userId: string, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.get<TData>(`/api/Users/${userId}`, options);
  }

  /**
   * @summary Updates a user.
   */
  updateUser<TData = AdminUserDto>(
    userId: string,
    adminUpdateUserRequestDto: AdminUpdateUserRequestDto,
    options?: HttpClientOptions & { observe?: "body" }
  ): Observable<TData>;
  updateUser<TData = AdminUserDto>(
    userId: string,
    adminUpdateUserRequestDto: AdminUpdateUserRequestDto,
    options?: HttpClientOptions & { observe: "events" }
  ): Observable<HttpEvent<TData>>;
  updateUser<TData = AdminUserDto>(
    userId: string,
    adminUpdateUserRequestDto: AdminUpdateUserRequestDto,
    options?: HttpClientOptions & { observe: "response" }
  ): Observable<AngularHttpResponse<TData>>;
  updateUser<TData = AdminUserDto>(
    userId: string,
    adminUpdateUserRequestDto: AdminUpdateUserRequestDto,
    options?: HttpClientOptions & { observe?: any }
  ): Observable<any> {
    return this.http.put<TData>(`/api/Users/${userId}`, adminUpdateUserRequestDto, options);
  }

  /**
   * @summary Deletes a user.
   */
  deleteUser<TData = boolean>(userId: string, options?: HttpClientOptions & { observe?: "body" }): Observable<TData>;
  deleteUser<TData = boolean>(userId: string, options?: HttpClientOptions & { observe: "events" }): Observable<HttpEvent<TData>>;
  deleteUser<TData = boolean>(userId: string, options?: HttpClientOptions & { observe: "response" }): Observable<AngularHttpResponse<TData>>;
  deleteUser<TData = boolean>(userId: string, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.delete<TData>(`/api/Users/${userId}`, options);
  }

  /**
   * @summary Retrieves a user by username.
   */
  getUserByUserName<TData = GetUserByUserName200One | GetUserByUserName200Two | GetUserByUserName200Three>(
    userName: string,
    options?: HttpClientOptions & { observe?: "body" }
  ): Observable<TData>;
  getUserByUserName<TData = GetUserByUserName200One | GetUserByUserName200Two | GetUserByUserName200Three>(
    userName: string,
    options?: HttpClientOptions & { observe: "events" }
  ): Observable<HttpEvent<TData>>;
  getUserByUserName<TData = GetUserByUserName200One | GetUserByUserName200Two | GetUserByUserName200Three>(
    userName: string,
    options?: HttpClientOptions & { observe: "response" }
  ): Observable<AngularHttpResponse<TData>>;
  getUserByUserName<TData = GetUserByUserName200One | GetUserByUserName200Two | GetUserByUserName200Three>(
    userName: string,
    options?: HttpClientOptions & { observe?: any }
  ): Observable<any> {
    return this.http.get<TData>(`/api/Users/user-name/${userName}`, options);
  }

  /**
   * @summary Searches for users based on the specified criteria.
   */
  searchUsers<TData = PublicUserDtoPagedResponseDto>(
    adminSearchUsersRequestDto: AdminSearchUsersRequestDto,
    options?: HttpClientOptions & { observe?: "body" }
  ): Observable<TData>;
  searchUsers<TData = PublicUserDtoPagedResponseDto>(
    adminSearchUsersRequestDto: AdminSearchUsersRequestDto,
    options?: HttpClientOptions & { observe: "events" }
  ): Observable<HttpEvent<TData>>;
  searchUsers<TData = PublicUserDtoPagedResponseDto>(
    adminSearchUsersRequestDto: AdminSearchUsersRequestDto,
    options?: HttpClientOptions & { observe: "response" }
  ): Observable<AngularHttpResponse<TData>>;
  searchUsers<TData = PublicUserDtoPagedResponseDto>(
    adminSearchUsersRequestDto: AdminSearchUsersRequestDto,
    options?: HttpClientOptions & { observe?: any }
  ): Observable<any> {
    return this.http.post<TData>(`/api/Users/search`, adminSearchUsersRequestDto, options);
  }

  /**
   * @summary Retrieves a list of users by their IDs.
   */
  getUsersByIds<TData = GetUsersByIds200OneItem[] | null | GetUsersByIds200TwoItem[] | null | GetUsersByIds200ThreeItem[] | null>(
    getUsersByIdsBody: string[],
    options?: HttpClientOptions & { observe?: "body" }
  ): Observable<TData>;
  getUsersByIds<TData = GetUsersByIds200OneItem[] | null | GetUsersByIds200TwoItem[] | null | GetUsersByIds200ThreeItem[] | null>(
    getUsersByIdsBody: string[],
    options?: HttpClientOptions & { observe: "events" }
  ): Observable<HttpEvent<TData>>;
  getUsersByIds<TData = GetUsersByIds200OneItem[] | null | GetUsersByIds200TwoItem[] | null | GetUsersByIds200ThreeItem[] | null>(
    getUsersByIdsBody: string[],
    options?: HttpClientOptions & { observe: "response" }
  ): Observable<AngularHttpResponse<TData>>;
  getUsersByIds<TData = GetUsersByIds200OneItem[] | null | GetUsersByIds200TwoItem[] | null | GetUsersByIds200ThreeItem[] | null>(
    getUsersByIdsBody: string[],
    options?: HttpClientOptions & { observe?: any }
  ): Observable<any> {
    return this.http.post<TData>(`/api/Users/get-by-ids`, getUsersByIdsBody, options);
  }

  /**
   * @summary Retrieves all available roles.
   */
  getRoles<TData = RoleDto[] | null>(options?: HttpClientOptions & { observe?: "body" }): Observable<TData>;
  getRoles<TData = RoleDto[] | null>(options?: HttpClientOptions & { observe: "events" }): Observable<HttpEvent<TData>>;
  getRoles<TData = RoleDto[] | null>(options?: HttpClientOptions & { observe: "response" }): Observable<AngularHttpResponse<TData>>;
  getRoles<TData = RoleDto[] | null>(options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.get<TData>(`/api/Users/roles`, options);
  }

  /**
   * @summary Retrieves the roles for a user.
   */
  getRolesForUser<TData = string[] | null>(userId: string, options?: HttpClientOptions & { observe?: "body" }): Observable<TData>;
  getRolesForUser<TData = string[] | null>(userId: string, options?: HttpClientOptions & { observe: "events" }): Observable<HttpEvent<TData>>;
  getRolesForUser<TData = string[] | null>(
    userId: string,
    options?: HttpClientOptions & { observe: "response" }
  ): Observable<AngularHttpResponse<TData>>;
  getRolesForUser<TData = string[] | null>(userId: string, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.get<TData>(`/api/Users/${userId}/roles`, options);
  }

  /**
   * @summary Retrieves the users in a specific role.
   */
  getUsersInRole<TData = AdminUserDto[] | null>(role: string, options?: HttpClientOptions & { observe?: "body" }): Observable<TData>;
  getUsersInRole<TData = AdminUserDto[] | null>(role: string, options?: HttpClientOptions & { observe: "events" }): Observable<HttpEvent<TData>>;
  getUsersInRole<TData = AdminUserDto[] | null>(
    role: string,
    options?: HttpClientOptions & { observe: "response" }
  ): Observable<AngularHttpResponse<TData>>;
  getUsersInRole<TData = AdminUserDto[] | null>(role: string, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.get<TData>(`/api/Users/roles/${role}`, options);
  }

  /**
   * @summary Adds a user to a role.
   */
  addUserToRole<TData = boolean>(role: string, userId: string, options?: HttpClientOptions & { observe?: "body" }): Observable<TData>;
  addUserToRole<TData = boolean>(role: string, userId: string, options?: HttpClientOptions & { observe: "events" }): Observable<HttpEvent<TData>>;
  addUserToRole<TData = boolean>(
    role: string,
    userId: string,
    options?: HttpClientOptions & { observe: "response" }
  ): Observable<AngularHttpResponse<TData>>;
  addUserToRole<TData = boolean>(role: string, userId: string, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.post<TData>(`/api/Users/roles/${role}/${userId}`, undefined, options);
  }

  /**
   * @summary Removes a user from a role.
   */
  removeUserFromRole<TData = boolean>(role: string, userId: string, options?: HttpClientOptions & { observe?: "body" }): Observable<TData>;
  removeUserFromRole<TData = boolean>(
    role: string,
    userId: string,
    options?: HttpClientOptions & { observe: "events" }
  ): Observable<HttpEvent<TData>>;
  removeUserFromRole<TData = boolean>(
    role: string,
    userId: string,
    options?: HttpClientOptions & { observe: "response" }
  ): Observable<AngularHttpResponse<TData>>;
  removeUserFromRole<TData = boolean>(role: string, userId: string, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.delete<TData>(`/api/Users/roles/${role}/${userId}`, options);
  }

  /**
   * @summary Searches claims.
   */
  searchClaims<TData = ClaimDtoPagedResponseDto>(
    searchClaimsBody: SearchClaimsBodyOne | SearchClaimsBodyTwo | SearchClaimsBodyThree,
    options?: HttpClientOptions & { observe?: "body" }
  ): Observable<TData>;
  searchClaims<TData = ClaimDtoPagedResponseDto>(
    searchClaimsBody: SearchClaimsBodyOne | SearchClaimsBodyTwo | SearchClaimsBodyThree,
    options?: HttpClientOptions & { observe: "events" }
  ): Observable<HttpEvent<TData>>;
  searchClaims<TData = ClaimDtoPagedResponseDto>(
    searchClaimsBody: SearchClaimsBodyOne | SearchClaimsBodyTwo | SearchClaimsBodyThree,
    options?: HttpClientOptions & { observe: "response" }
  ): Observable<AngularHttpResponse<TData>>;
  searchClaims<TData = ClaimDtoPagedResponseDto>(
    searchClaimsBody: SearchClaimsBodyOne | SearchClaimsBodyTwo | SearchClaimsBodyThree,
    options?: HttpClientOptions & { observe?: any }
  ): Observable<any> {
    return this.http.post<TData>(`/api/Users/claims/search`, searchClaimsBody, options);
  }

  /**
   * @summary Searches user claims.
   */
  searchUserClaims<TData = UserClaimDtoPagedResponseDto>(
    searchUserClaimsRequestDto: SearchUserClaimsRequestDto,
    options?: HttpClientOptions & { observe?: "body" }
  ): Observable<TData>;
  searchUserClaims<TData = UserClaimDtoPagedResponseDto>(
    searchUserClaimsRequestDto: SearchUserClaimsRequestDto,
    options?: HttpClientOptions & { observe: "events" }
  ): Observable<HttpEvent<TData>>;
  searchUserClaims<TData = UserClaimDtoPagedResponseDto>(
    searchUserClaimsRequestDto: SearchUserClaimsRequestDto,
    options?: HttpClientOptions & { observe: "response" }
  ): Observable<AngularHttpResponse<TData>>;
  searchUserClaims<TData = UserClaimDtoPagedResponseDto>(
    searchUserClaimsRequestDto: SearchUserClaimsRequestDto,
    options?: HttpClientOptions & { observe?: any }
  ): Observable<any> {
    return this.http.post<TData>(`/api/Users/user-claims/search`, searchUserClaimsRequestDto, options);
  }

  /**
   * @summary Returns users with a specific claim.
   */
  getUsersWithClaim<TData = StringPagedResponseDto>(
    searchClaimRequestDto: SearchClaimRequestDto,
    options?: HttpClientOptions & { observe?: "body" }
  ): Observable<TData>;
  getUsersWithClaim<TData = StringPagedResponseDto>(
    searchClaimRequestDto: SearchClaimRequestDto,
    options?: HttpClientOptions & { observe: "events" }
  ): Observable<HttpEvent<TData>>;
  getUsersWithClaim<TData = StringPagedResponseDto>(
    searchClaimRequestDto: SearchClaimRequestDto,
    options?: HttpClientOptions & { observe: "response" }
  ): Observable<AngularHttpResponse<TData>>;
  getUsersWithClaim<TData = StringPagedResponseDto>(
    searchClaimRequestDto: SearchClaimRequestDto,
    options?: HttpClientOptions & { observe?: any }
  ): Observable<any> {
    return this.http.post<TData>(`/api/Users/claim-users`, searchClaimRequestDto, options);
  }

  /**
   * @summary Adds a claim to a user.
   */
  addUserClaim<TData = boolean>(
    userId: string,
    addUserClaimBody: AddUserClaimBodyOne | AddUserClaimBodyTwo | AddUserClaimBodyThree,
    options?: HttpClientOptions & { observe?: "body" }
  ): Observable<TData>;
  addUserClaim<TData = boolean>(
    userId: string,
    addUserClaimBody: AddUserClaimBodyOne | AddUserClaimBodyTwo | AddUserClaimBodyThree,
    options?: HttpClientOptions & { observe: "events" }
  ): Observable<HttpEvent<TData>>;
  addUserClaim<TData = boolean>(
    userId: string,
    addUserClaimBody: AddUserClaimBodyOne | AddUserClaimBodyTwo | AddUserClaimBodyThree,
    options?: HttpClientOptions & { observe: "response" }
  ): Observable<AngularHttpResponse<TData>>;
  addUserClaim<TData = boolean>(
    userId: string,
    addUserClaimBody: AddUserClaimBodyOne | AddUserClaimBodyTwo | AddUserClaimBodyThree,
    options?: HttpClientOptions & { observe?: any }
  ): Observable<any> {
    return this.http.post<TData>(`/api/Users/${userId}/claims`, addUserClaimBody, options);
  }

  /**
   * @summary Removes a claim from a user.
   */
  removeUserClaim<TData = boolean>(
    userId: string,
    removeUserClaimBody: RemoveUserClaimBodyOne | RemoveUserClaimBodyTwo | RemoveUserClaimBodyThree,
    options?: HttpClientOptions & { observe?: "body" }
  ): Observable<TData>;
  removeUserClaim<TData = boolean>(
    userId: string,
    removeUserClaimBody: RemoveUserClaimBodyOne | RemoveUserClaimBodyTwo | RemoveUserClaimBodyThree,
    options?: HttpClientOptions & { observe: "events" }
  ): Observable<HttpEvent<TData>>;
  removeUserClaim<TData = boolean>(
    userId: string,
    removeUserClaimBody: RemoveUserClaimBodyOne | RemoveUserClaimBodyTwo | RemoveUserClaimBodyThree,
    options?: HttpClientOptions & { observe: "response" }
  ): Observable<AngularHttpResponse<TData>>;
  removeUserClaim<TData = boolean>(
    userId: string,
    removeUserClaimBody: RemoveUserClaimBodyOne | RemoveUserClaimBodyTwo | RemoveUserClaimBodyThree,
    options?: HttpClientOptions & { observe?: any }
  ): Observable<any> {
    return this.http.delete<TData>(`/api/Users/${userId}/claims`, { body: removeUserClaimBody, ...options });
  }

  /**
   * @summary Locks a user account.
   */
  lockUserAccount<TData = boolean>(userId: string, options?: HttpClientOptions & { observe?: "body" }): Observable<TData>;
  lockUserAccount<TData = boolean>(userId: string, options?: HttpClientOptions & { observe: "events" }): Observable<HttpEvent<TData>>;
  lockUserAccount<TData = boolean>(userId: string, options?: HttpClientOptions & { observe: "response" }): Observable<AngularHttpResponse<TData>>;
  lockUserAccount<TData = boolean>(userId: string, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.post<TData>(`/api/Users/${userId}/lock`, undefined, options);
  }

  /**
   * @summary Unlocks a user account.
   */
  unlockUserAccount<TData = boolean>(userId: string, options?: HttpClientOptions & { observe?: "body" }): Observable<TData>;
  unlockUserAccount<TData = boolean>(userId: string, options?: HttpClientOptions & { observe: "events" }): Observable<HttpEvent<TData>>;
  unlockUserAccount<TData = boolean>(userId: string, options?: HttpClientOptions & { observe: "response" }): Observable<AngularHttpResponse<TData>>;
  unlockUserAccount<TData = boolean>(userId: string, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.post<TData>(`/api/Users/${userId}/unlock`, undefined, options);
  }

  /**
   * @summary Gets the settings for a user.
   */
  getUserSettings<TData = UserSettingDto[] | null>(userId: string, options?: HttpClientOptions & { observe?: "body" }): Observable<TData>;
  getUserSettings<TData = UserSettingDto[] | null>(userId: string, options?: HttpClientOptions & { observe: "events" }): Observable<HttpEvent<TData>>;
  getUserSettings<TData = UserSettingDto[] | null>(
    userId: string,
    options?: HttpClientOptions & { observe: "response" }
  ): Observable<AngularHttpResponse<TData>>;
  getUserSettings<TData = UserSettingDto[] | null>(userId: string, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.get<TData>(`/api/Users/${userId}/settings`, options);
  }

  /**
 * This method requires the caller to have the Administrator role. It is intended to be
            used for managing user-specific settings.
 * @summary Updates the settings for a specific user.
 */
  setUserSetting<TData = UserSettingDto>(
    userId: string,
    setUserSettingRequestDto: SetUserSettingRequestDto,
    options?: HttpClientOptions & { observe?: "body" }
  ): Observable<TData>;
  setUserSetting<TData = UserSettingDto>(
    userId: string,
    setUserSettingRequestDto: SetUserSettingRequestDto,
    options?: HttpClientOptions & { observe: "events" }
  ): Observable<HttpEvent<TData>>;
  setUserSetting<TData = UserSettingDto>(
    userId: string,
    setUserSettingRequestDto: SetUserSettingRequestDto,
    options?: HttpClientOptions & { observe: "response" }
  ): Observable<AngularHttpResponse<TData>>;
  setUserSetting<TData = UserSettingDto>(
    userId: string,
    setUserSettingRequestDto: SetUserSettingRequestDto,
    options?: HttpClientOptions & { observe?: any }
  ): Observable<any> {
    return this.http.put<TData>(`/api/Users/${userId}/settings`, setUserSettingRequestDto, options);
  }
}

export type GetPublishedStaticContentClientResult = NonNullable<PublishedStaticContentResultDto>;
export type GetSupportedLanguagesClientResult = NonNullable<StaticContentSupportedLanguageDto[] | null>;
export type CreateStaticContentClientResult = NonNullable<StaticContentDto>;
export type GetStaticContentClientResult = NonNullable<StaticContentDto>;
export type UpdateStaticContentClientResult = NonNullable<StaticContentDto>;
export type DeleteStaticContentClientResult = NonNullable<boolean>;
export type SearchStaticContentClientResult = NonNullable<StaticContentDtoPagedResponseDto>;
export type GetStaticContentLanguageClientResult = NonNullable<StaticContentLanguageDto>;
export type CreateStaticContentLanguageClientResult = NonNullable<StaticContentLanguageDto>;
export type UpdateStaticContentLanguageClientResult = NonNullable<StaticContentLanguageDto>;
export type DeleteStaticContentLanguageClientResult = NonNullable<boolean>;
export type GetStaticContentLanguagesClientResult = NonNullable<StaticContentLanguageDto[] | null>;
export type GetSupportedExternalLoginsClientResult = NonNullable<SupportedExternalLoginDto[] | null>;
export type SearchExternalLoginsClientResult = NonNullable<AdminExternalLoginDtoPagedResponseDto>;
export type RemoveExternalLoginClientResult = NonNullable<boolean>;
export type GetExternalLoginResultClientResult = NonNullable<ExternalLoginSuccessDto>;
export type CompleteExternalLoginClientResult = NonNullable<LoginSuccessDto>;
export type CompleteExternalLoginRegistrationClientResult = NonNullable<LoginSuccessDto>;
export type LogInClientResult = NonNullable<LoginSuccessDto>;
export type RegisterClientResult = NonNullable<LoginSuccessDto>;
export type LogOutClientResult = NonNullable<boolean>;
export type ChangePasswordClientResult = NonNullable<boolean>;
export type ChangeEmailClientResult = NonNullable<boolean>;
export type ConfirmEmailChangeClientResult = NonNullable<boolean>;
export type ResetPasswordClientResult = NonNullable<boolean>;
export type NewPasswordClientResult = NonNullable<LoginSuccessDto>;
export type VerifyCodeClientResult = NonNullable<string | null>;
export type GetAccessTokenClientResult = NonNullable<string | null>;
export type RequestVerificationEmailClientResult = NonNullable<boolean>;
export type VerifyEmailClientResult = NonNullable<boolean>;
export type RequestMagicLinkEmailClientResult = NonNullable<boolean>;
export type GetDevicesClientResult = NonNullable<DeviceDto[] | null>;
export type RevokeDeviceClientResult = NonNullable<boolean>;
export type GetProfileClientResult = NonNullable<ProfileDto>;
export type UpdateMyProfileClientResult = NonNullable<ProfileDto>;
export type SearchMyNotificationsClientResult = NonNullable<NotificationSearchResultsDto>;
export type MarkAllMyNotificationsAsReadClientResult = NonNullable<boolean>;
export type MarkMyNotificationAsReadClientResult = NonNullable<boolean>;
export type GetMyUserClaimsClientResult = NonNullable<ClaimDtoPagedResponseDto>;
export type GetMyUserSettingsClientResult = NonNullable<UserSettingDto[] | null>;
export type SetMyUserSettingClientResult = NonNullable<UserSettingDto>;
export type GetMyExternalLoginsClientResult = NonNullable<
  GetMyExternalLogins200OneItem[] | null | GetMyExternalLogins200TwoItem[] | null | GetMyExternalLogins200ThreeItem[] | null
>;
export type RemoveMyExternalLoginClientResult = NonNullable<boolean>;
export type GetUserClientResult = NonNullable<GetUser200One | GetUser200Two | GetUser200Three>;
export type UpdateUserClientResult = NonNullable<AdminUserDto>;
export type DeleteUserClientResult = NonNullable<boolean>;
export type GetUserByUserNameClientResult = NonNullable<GetUserByUserName200One | GetUserByUserName200Two | GetUserByUserName200Three>;
export type SearchUsersClientResult = NonNullable<PublicUserDtoPagedResponseDto>;
export type GetUsersByIdsClientResult = NonNullable<
  GetUsersByIds200OneItem[] | null | GetUsersByIds200TwoItem[] | null | GetUsersByIds200ThreeItem[] | null
>;
export type GetRolesClientResult = NonNullable<RoleDto[] | null>;
export type GetRolesForUserClientResult = NonNullable<string[] | null>;
export type GetUsersInRoleClientResult = NonNullable<AdminUserDto[] | null>;
export type AddUserToRoleClientResult = NonNullable<boolean>;
export type RemoveUserFromRoleClientResult = NonNullable<boolean>;
export type SearchClaimsClientResult = NonNullable<ClaimDtoPagedResponseDto>;
export type SearchUserClaimsClientResult = NonNullable<UserClaimDtoPagedResponseDto>;
export type GetUsersWithClaimClientResult = NonNullable<StringPagedResponseDto>;
export type AddUserClaimClientResult = NonNullable<boolean>;
export type RemoveUserClaimClientResult = NonNullable<boolean>;
export type LockUserAccountClientResult = NonNullable<boolean>;
export type UnlockUserAccountClientResult = NonNullable<boolean>;
export type GetUserSettingsClientResult = NonNullable<UserSettingDto[] | null>;
export type SetUserSettingClientResult = NonNullable<UserSettingDto>;
