/**
 * Mock services and objects for testing
 *
 * Note: HTTP API mocks are now generated by Orval in src/app/core/backend-api/services/lightnap-api.ts
 * These mock services provide application-level state and feature mocks that Orval doesn't generate.
 */

export * from "./mock-identity.service";
export * from "./mock-route-alias.service";
export * from "./mock-toast.service";
export * from "./mock-initialization.service";
export * from "./mock-timer.service";
