/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */
import type { ClaimDto } from "./claim-dto";
import type { UserClaimDto } from "./user-claim-dto";

/**
 * Represents a claim.
 */
export type AddUserClaimBodyTwo = ClaimDto | UserClaimDto;
