/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */
import type { AdminUserDto } from "./admin-user-dto";
import type { ApiResponseType } from "./api-response-type";

/**
 * Represents the response of an API call.
 */
export interface AdminUserDtoApiResponseDto {
  result?: AdminUserDto;
  type: ApiResponseType;
  /**
   * Gets or sets the error messages associated with the API response.
   * @nullable
   */
  errorMessages?: string[] | null;
}
