/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */

/**
 * The data transfer object for updating a user. Update fields here when editable user fields change.
 */
export interface AdminUpdateUserRequestDto {
  [key: string]: unknown;
}
