/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */
import type { IntegrationDto } from "./integration-dto";

/**
 * DTO for admin-level search results for user integrations.
 */
export type AdminIntegrationDto = IntegrationDto & {
  /** The user ID. */
  userId: string;
} & Required<
    Pick<
      IntegrationDto & {
        /** The user ID. */
        userId: string;
      },
      "userId"
    >
  >;
