/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */
import type { PrivilegedUserDto } from "./privileged-user-dto";

/**
 * Represents a user DTO with public information.
 */
export type AdminUserDto = PrivilegedUserDto & {
  /** The last modified date of the user. */
  lastModifiedDate: Date;
  /**
   * When the user's lockout ends, if applicable.
   * @nullable
   */
  lockoutEnd?: Date | null;
} & Required<
    Pick<
      PrivilegedUserDto & {
        /** The last modified date of the user. */
        lastModifiedDate: Date;
        /**
         * When the user's lockout ends, if applicable.
         * @nullable
         */
        lockoutEnd?: Date | null;
      },
      "lastModifiedDate"
    >
  >;
