/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */
import type { ExternalLoginDto } from "./external-login-dto";

/**
 * Represents external login information for an administrative user, including the user's identifier and associated
external authentication details.
 */
export type AdminExternalLoginDto = ExternalLoginDto & {
  /** The unique identifier of the administrative user associated with the external login. */
  userId: string;
} & Required<
    Pick<
      ExternalLoginDto & {
        /** The unique identifier of the administrative user associated with the external login. */
        userId: string;
      },
      "userId"
    >
  >;
