/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */
import type { AdminExternalLoginDtoPagedResponseDto } from "./admin-external-login-dto-paged-response-dto";
import type { ApiResponseType } from "./api-response-type";

/**
 * Represents the response of an API call.
 */
export interface AdminExternalLoginDtoPagedResponseDtoApiResponseDto {
  result?: AdminExternalLoginDtoPagedResponseDto;
  type: ApiResponseType;
  /**
   * Gets or sets the error messages associated with the API response.
   * @nullable
   */
  errorMessages?: string[] | null;
}
