/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */

/**
 * Represents external login information for an administrative user, including the user's identifier and associated
external authentication details.
 */
export interface AdminExternalLoginDto {
  /** The name of the external authentication provider (for example, "Google" or "Facebook"). */
  loginProvider: string;
  /** The unique identifier assigned to the user by the external authentication provider. */
  providerKey: string;
  /** The display name of the external authentication provider, as shown to users. */
  providerDisplayName: string;
  /** The unique identifier of the administrative user associated with the external login. */
  userId: string;
}
