/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */

/**
 * Represents the response types for an API.
 */
export type ApiResponseType = (typeof ApiResponseType)[keyof typeof ApiResponseType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ApiResponseType = {
  Success: "Success",
  Error: "Error",
  UnexpectedError: "UnexpectedError",
} as const;
