/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */

/**
 * Supported user sorting options.
 */
export type ApplicationUserSortBy = (typeof ApplicationUserSortBy)[keyof typeof ApplicationUserSortBy];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ApplicationUserSortBy = {
  Email: "Email",
  UserName: "UserName",
  CreatedDate: "CreatedDate",
  LastModifiedDate: "LastModifiedDate",
} as const;
