/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */

/**
 * Supported CAPTCHA providers.
 */
export type CaptchaProvider = (typeof CaptchaProvider)[keyof typeof CaptchaProvider];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CaptchaProvider = {
  None: "None",
  Turnstile: "Turnstile",
  RecaptchaV2: "RecaptchaV2",
  RecaptchaV3: "RecaptchaV3",
} as const;
