/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */
import type { CaptchaProvider } from "./captcha-provider";

/**
 * Browser-safe subset of the CAPTCHA configuration. Exposes the active provider and the
public site key (when applicable) so an SPA can render the matching widget. Never
exposes any secret key.
 */
export interface CaptchaClientConfigDto {
  provider: CaptchaProvider;
  /**
   * Public site key for the active provider, or null when LightNap.Core.Captcha.Dto.Response.CaptchaClientConfigDto.Provider is
LightNap.Core.Configuration.Captcha.CaptchaProvider.None.
   * @nullable
   */
  siteKey?: string | null;
}
