/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */

/**
 * Data transfer object for requesting an email change.
 */
export interface ChangeEmailRequestDto {
  /**
   * The email to change to.
   * @minLength 0
   * @maxLength 256
   */
  newEmail: string;
}
