/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */

/**
 * Data transfer object for requesting a password change.
 */
export interface ChangePasswordRequestDto {
  /**
   * Gets or sets the current password of the user.
   * @minLength 0
   * @maxLength 256
   */
  currentPassword: string;
  /**
   * Gets or sets the new password.
   * @minLength 0
   * @maxLength 256
   */
  newPassword: string;
  /**
   * Gets or sets the confirmation of the new password.
   * @minLength 0
   * @maxLength 256
   */
  confirmNewPassword: string;
}
