/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */

/**
 * Represents a claim.
 */
export interface ClaimDto {
  /** Gets or sets the claim type. */
  type: string;
  /** Gets or sets the claim value. */
  value: string;
}
