/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */
import type { ExternalLoginRequestDto } from "./external-login-request-dto";
import type { ExternalLoginRegisterRequestDto } from "./external-login-register-request-dto";

/**
 * Represents the data transfer object for completing external login completion.
 */
export type CompleteExternalLoginBodyThree = ExternalLoginRequestDto | ExternalLoginRegisterRequestDto;
