/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */

/**
 * DTO for confirming an OAuth integration.
 */
export interface ConfirmIntegrationRequestDto {
  /** The confirmation token. */
  confirmationToken: string;
}
