/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */

/**
 * Data transfer object for confirming an email change.
 */
export interface ConfirmEmailChangeRequestDto {
  /**
   * The email to change to.
   * @minLength 0
   * @maxLength 256
   */
  newEmail: string;
  /**
   * The change confirmation code.
   * @minLength 0
   * @maxLength 512
   */
  code: string;
}
