/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */
import type { UpdateIntegrationRequestDto } from "./update-integration-request-dto";

/**
 * DTO for creating an integration.
 */
export type CreateIntegrationRequestDto = UpdateIntegrationRequestDto & {
  /** The integration provider. */
  provider: string;
} & Required<
    Pick<
      UpdateIntegrationRequestDto & {
        /** The integration provider. */
        provider: string;
      },
      "provider"
    >
  >;
