/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */
import type { UpdateStaticContentLanguageDto } from "./update-static-content-language-dto";

export type CreateStaticContentLanguageDto = UpdateStaticContentLanguageDto;
