/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */
import type { UpdateIntegrationRequestDto } from "./update-integration-request-dto";
import type { IntegrationProvider } from "./integration-provider";

/**
 * DTO for creating an integration.
 */
export type CreateIntegrationRequestDto = UpdateIntegrationRequestDto & {
  provider: IntegrationProvider;
} & Required<
    Pick<
      UpdateIntegrationRequestDto & {
        provider: IntegrationProvider;
      },
      "provider"
    >
  >;
