/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */
import type { CreateIntegrationRequestDto } from "./create-integration-request-dto";

/**
 * DTO for creating an integration from an OAuth process.
 */
export type CreateIntegrationFromOAuthRequestDto = CreateIntegrationRequestDto & {
  /**
   * The refresh token.
   * @nullable
   */
  refreshToken?: string | null;
  /**
   * When the access token expires.
   * @nullable
   */
  credentialsExpiration?: Date | null;
  /**
   * When the user will need to re-authorize.
   * @nullable
   */
  authorizationExpiration?: Date | null;
};
