/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */

/**
 * Data transfer object representing a device.
 */
export interface DeviceDto {
  /** Gets or sets the unique identifier of the device. */
  id: string;
  /** Gets or sets the timestamp of the last time the device was seen. */
  lastSeen: Date;
  /** Gets or sets the IP address of the device. */
  ipAddress: string;
  /** Gets or sets additional details about the device. */
  details: string;
}
