/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */
import type { ExternalLoginRequestDto } from "./external-login-request-dto";

/**
 * Represents the data transfer object for completing external login registration.
 */
export type ExternalLoginRegisterRequestDto = ExternalLoginRequestDto & {
  /**
   * Gets or sets the email address of the user.
   * @minLength 0
   * @maxLength 32
   */
  email: string;
  /**
   * Gets or sets the username of the user.
   * @minLength 0
   * @maxLength 32
   */
  userName: string;
  /** Whether the user is opting into marketing email at registration. */
  marketingOptIn: boolean;
} & Required<
    Pick<
      ExternalLoginRequestDto & {
        /**
         * Gets or sets the email address of the user.
         * @minLength 0
         * @maxLength 32
         */
        email: string;
        /**
         * Gets or sets the username of the user.
         * @minLength 0
         * @maxLength 32
         */
        userName: string;
        /** Whether the user is opting into marketing email at registration. */
        marketingOptIn: boolean;
      },
      "email" | "marketingOptIn" | "userName"
    >
  >;
