/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */

/**
 * Represents external login information for a user, including the authentication provider and associated identifiers.
 */
export interface ExternalLoginDto {
  /** The name of the external authentication provider (for example, "Google" or "Facebook"). */
  loginProvider: string;
  /** The unique identifier assigned to the user by the external authentication provider. */
  providerKey: string;
  /** The display name of the external authentication provider, as shown to users. */
  providerDisplayName: string;
}
