/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */
import type { ExternalLoginSuccessDto } from "./external-login-success-dto";
import type { ApiResponseType } from "./api-response-type";

/**
 * Represents the response of an API call.
 */
export interface ExternalLoginSuccessDtoApiResponseDto {
  result?: ExternalLoginSuccessDto;
  type: ApiResponseType;
  /**
   * Gets or sets the error messages associated with the API response.
   * @nullable
   */
  errorMessages?: string[] | null;
}
