/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */
import type { ExternalLoginSuccessType } from "./external-login-success-type";

/**
 * Represents the result of a successful external login operation.
 */
export interface ExternalLoginSuccessDto {
  type: ExternalLoginSuccessType;
  /**
   * Provided when the external login requires registration and included an email.
   * @nullable
   */
  email?: string | null;
  /**
   * Provided when the external login requires registration and included a user name.
   * @nullable
   */
  userName?: string | null;
}
