/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */

/**
 * Represents the data transfer object for completing external login registration.
 */
export interface ExternalLoginRegisterRequestDto {
  /** Gets or sets a value indicating whether to remember the user. */
  rememberMe: boolean;
  /**
   * Gets or sets the device details of the user.
   * @minLength 0
   * @maxLength 512
   */
  deviceDetails: string;
  /**
   * Gets or sets the email address of the user.
   * @minLength 0
   * @maxLength 32
   */
  email: string;
  /**
   * Gets or sets the username of the user.
   * @minLength 0
   * @maxLength 32
   */
  userName: string;
}
