/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */

/**
 * Represents the result of a successful external login operation.
 */
export type ExternalLoginSuccessType = (typeof ExternalLoginSuccessType)[keyof typeof ExternalLoginSuccessType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ExternalLoginSuccessType = {
  AlreadyLinkedToDifferentAccount: "AlreadyLinkedToDifferentAccount",
  AlreadyLinked: "AlreadyLinked",
  NewAccountLink: "NewAccountLink",
  RequiresRegistration: "RequiresRegistration",
} as const;
