/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */
import type { PagedRequestDtoBase } from "./paged-request-dto-base";
import type { AdminSearchUsersRequestDto } from "./admin-search-users-request-dto";
import type { PrivilegedSearchUsersRequestDto } from "./privileged-search-users-request-dto";
import type { PublicSearchUsersRequestDto } from "./public-search-users-request-dto";
import type { SearchClaimRequestDto } from "./search-claim-request-dto";
import type { SearchClaimsRequestDto } from "./search-claims-request-dto";
import type { SearchUserClaimsRequestDto } from "./search-user-claims-request-dto";
import type { SearchStaticContentRequestDto } from "./search-static-content-request-dto";
import type { SearchNotificationsRequestDto } from "./search-notifications-request-dto";
import type { SearchExternalLoginsRequestDto } from "./search-external-logins-request-dto";

/**
 * Base class for pagination requests.
 */
export type GetMyUserClaimsBodyTwo =
  | PagedRequestDtoBase
  | AdminSearchUsersRequestDto
  | PrivilegedSearchUsersRequestDto
  | PublicSearchUsersRequestDto
  | SearchClaimRequestDto
  | SearchClaimsRequestDto
  | SearchUserClaimsRequestDto
  | SearchStaticContentRequestDto
  | SearchNotificationsRequestDto
  | SearchExternalLoginsRequestDto;
