/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */
import type { PublicUserDto } from "./public-user-dto";
import type { AdminUserDto } from "./admin-user-dto";
import type { PrivilegedUserDto } from "./privileged-user-dto";

/**
 * Represents a user DTO with public information.
 */
export type GetUsersByIds200OneItem = PublicUserDto | AdminUserDto | PrivilegedUserDto;
