/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */
import type { PublicUserDto } from "./public-user-dto";
import type { AdminUserDto } from "./admin-user-dto";
import type { PrivilegedUserDto } from "./privileged-user-dto";

/**
 * Gets or sets the result of the API call.
 * @nullable
 */
export type GetUserByUserName200Three = PublicUserDto | AdminUserDto | PrivilegedUserDto | null;
