/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */

/**
 * Represents supported integration features.
 */
export type IntegrationFeature = (typeof IntegrationFeature)[keyof typeof IntegrationFeature];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const IntegrationFeature = {
  TestFeature: "TestFeature",
  Email: "Email",
} as const;
