/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */

/**
 * Represents the integration providers available in the system.
 */
export type IntegrationProvider = (typeof IntegrationProvider)[keyof typeof IntegrationProvider];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const IntegrationProvider = {
  TestProvider: "TestProvider",
  TestProviderManual: "TestProviderManual",
  Gmail: "Gmail",
} as const;
