/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */

/**
 * Represents the categories of integration types.
 */
export type IntegrationCategory = (typeof IntegrationCategory)[keyof typeof IntegrationCategory];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const IntegrationCategory = {
  TestCategory: "TestCategory",
} as const;
