/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */

/**
 * Represents supported integration services.
 */
export type IntegrationService = (typeof IntegrationService)[keyof typeof IntegrationService];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const IntegrationService = {
  TestService: "TestService",
} as const;
