/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */
import type { IntegrationProvider } from "./integration-provider";
import type { IntegrationFeature } from "./integration-feature";

/**
 * Represents an integration definition.
 */
export interface IntegrationProviderDefinition {
  provider: IntegrationProvider;
  /** The display name of the integration. */
  displayName: string;
  /** The description of the integration. */
  description: string;
  /** The features this integration supports. */
  features: IntegrationFeature[];
  /** True if the integration is configured manually by the user on the frontend. Otherwise the user will be sent to the backend for OAuth or similar flows. */
  isConfiguredManually: boolean;
}
