/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */
import type { IntegrationFeature } from "./integration-feature";

/**
 * Represents an integration definition.
 */
export interface IntegrationProviderDefinition {
  /** The integration provider key. */
  key: string;
  /** The organization the provider functionality belongs to, such as Google, Microsoft, etc. */
  organization: string;
  /** The display name of the provider. */
  displayName: string;
  /** The description of the provider. */
  description: string;
  /** Gets the collection of features supported by the integration. */
  features: IntegrationFeature[];
  /** True if the user needs to be redirected to the backend for OAuth or similar flows. If false, the user can enter
credentials, such as API keys, directly on the frontend. */
  requiresBackendConfiguration: boolean;
}
