/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */
import type { IntegrationProvider } from "./integration-provider";
import type { IntegrationFeature } from "./integration-feature";

/**
 * Represents an integration definition.
 */
export interface IntegrationProviderDefinition {
  provider: IntegrationProvider;
  /** The display name of the integration. */
  displayName: string;
  /** The features this integration supports. */
  features: IntegrationFeature[];
}
