/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */
import type { IntegrationProvider } from "./integration-provider";

/**
 * DTO for a user integration.
 */
export interface IntegrationDto {
  /** The ID. */
  id: number;
  /** When the integration was created. */
  createdDate: Date;
  provider: IntegrationProvider;
  /**
   * The expiration for integrations that can be automatically refreshed.
   * @nullable
   */
  credentialsExpiration?: Date | null;
  /**
   * The expiration for integrations that need to be manually reauthorized.
   * @nullable
   */
  authorizationExpiration?: Date | null;
  /** THe last time the integration was updated. */
  lastUpdated: Date;
  /** The friendly name of the integration. */
  friendlyName: string;
  /** True if the credentials should be included when the user requests the integration from a client request. */
  shareWithClient: boolean;
  /**
   * The credentials, if shared with the client.
   * @nullable
   */
  credentials?: string | null;
  /** True if the integration is expired. */
  isExpired: boolean;
  /**
   * The active error, if any.
   * @nullable
   */
  error?: string | null;
}
