/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */
import type { IntegrationFeature } from "./integration-feature";

/**
 * Defines a feature supported via integration.
 */
export interface IntegrationFeatureDefinition {
  feature: IntegrationFeature;
  /** The display name of the category. */
  displayName: string;
}
