/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */
import type { IntegrationType } from "./integration-type";
import type { IntegrationService } from "./integration-service";

/**
 * Represents an integration definition.
 */
export interface IntegrationDefinition {
  type: IntegrationType;
  /** The display name of the integration. */
  displayName: string;
  /** The services this integration supports. */
  services: IntegrationService[];
}
