/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */
import type { IntegrationCategory } from "./integration-category";
import type { IntegrationFeature } from "./integration-feature";

/**
 * Defines a category of integrations.
 */
export interface IntegrationCategoryDefinition {
  category: IntegrationCategory;
  /** The display name of the category. */
  displayName: string;
  /** The features this category includes. */
  features: IntegrationFeature[];
}
