/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */

/**
 * Represents the integration types available in the system.
 */
export type IntegrationType = (typeof IntegrationType)[keyof typeof IntegrationType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const IntegrationType = {
  TestType: "TestType",
} as const;
