/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */

/**
 * Indicates the specific type of login field provided in a login attempt.
 */
export type LoginType = (typeof LoginType)[keyof typeof LoginType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LoginType = {
  Unknown: "Unknown",
  Email: "Email",
  UserName: "UserName",
  MagicLink: "MagicLink",
} as const;
