/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */
import type { LoginType } from "./login-type";

/**
 * Represents the login request data transfer object.
 */
export interface LoginRequestDto {
  type?: LoginType;
  /**
   * The login identifier.
   * @minLength 0
   * @maxLength 256
   */
  login: string;
  /**
   * Gets or sets the password.
   * @minLength 0
   * @maxLength 256
   */
  password: string;
  /** Gets or sets a value indicating whether to remember the user. */
  rememberMe: boolean;
  /**
   * Gets or sets the device details.
   * @minLength 0
   * @maxLength 512
   */
  deviceDetails: string;
}
