/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */
import type { LoginSuccessType } from "./login-success-type";

/**
 * Represents the result of a successful login operation.
 */
export interface LoginSuccessDto {
  type: LoginSuccessType;
  /**
   * Gets or sets the access token for the authenticated user.
   * @nullable
   */
  accessToken?: string | null;
}
