/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */

/**
 * Represents the result of a successful login operation.
 */
export type LoginSuccessType = (typeof LoginSuccessType)[keyof typeof LoginSuccessType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LoginSuccessType = {
  AccessToken: "AccessToken",
  EmailVerificationRequired: "EmailVerificationRequired",
  TwoFactorRequired: "TwoFactorRequired",
} as const;
