/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */

/**
 * Represents the data transfer object for a new password request.
 */
export interface NewPasswordRequestDto {
  /**
   * Gets or sets the email address of the user.
   * @minLength 0
   * @maxLength 256
   */
  email: string;
  /**
   * Gets or sets the password reset token.
   * @minLength 0
   * @maxLength 512
   */
  token: string;
  /**
   * Gets or sets the new password.
   * @minLength 0
   * @maxLength 256
   */
  password: string;
  /** Gets or sets a value indicating whether to remember the user. */
  rememberMe: boolean;
  /**
   * Gets or sets the device details.
   * @minLength 0
   * @maxLength 512
   */
  deviceDetails: string;
}
