/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */

export type NotificationStatus = (typeof NotificationStatus)[keyof typeof NotificationStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NotificationStatus = {
  Unread: "Unread",
  Read: "Read",
  Archived: "Archived",
} as const;
