/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */
import type { NotificationStatus } from "./notification-status";
import type { NotificationType } from "./notification-type";
import type { NotificationDtoData } from "./notification-dto-data";

/**
 * Represents a notification data transfer object.
 */
export interface NotificationDto {
  /** Gets or sets the notification identifier. */
  id: number;
  /** Gets or sets the timestamp of the notification. */
  timestamp: string;
  status: NotificationStatus;
  type: NotificationType;
  /** Gets or sets the additional data associated with the notification. */
  data: NotificationDtoData;
}
