/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */

/**
 * Gets or sets the additional data associated with the notification.
 */
export type NotificationDtoData = { [key: string]: unknown };
