/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */
import type { PublicSearchUsersRequestDto } from "./public-search-users-request-dto";

/**
 * Represents a request to search users.
 */
export type PrivilegedSearchUsersRequestDto = PublicSearchUsersRequestDto;
