/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */
import type { PublicUserDto } from "./public-user-dto";

/**
 * Represents a data transfer object for a user with elevated privileges, extending the public user information
with additional properties.
 */
export type PrivilegedUserDto = PublicUserDto & {
  /** The email of the user. */
  email: string;
} & Required<
    Pick<
      PublicUserDto & {
        /** The email of the user. */
        email: string;
      },
      "email"
    >
  >;
