/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */

/**
 * Data transfer object representing the logged-in user's profile.
 */
export interface ProfileDto {
  /** Gets or sets the unique identifier of the user profile. */
  id: string;
  /** Gets or sets the email address of the user. */
  email: string;
  /** Gets or sets the username of the user. */
  userName: string;
}
