/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */

/**
 * Represents a user DTO with public information.
 */
export interface PublicUserDto {
  /** The ID of the user. */
  id: string;
  /** The username of the user. */
  userName: string;
  /** The created date of the user. */
  createdDate: Date;
}
