/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */
import type { PagedRequestDtoBase } from "./paged-request-dto-base";
import type { ApplicationUserSortBy } from "./application-user-sort-by";

/**
 * Represents a request to search users.
 */
export type PublicSearchUsersRequestDto = PagedRequestDtoBase & {
  /**
   * Gets or sets the email of the user.
   * @nullable
   */
  email?: string | null;
  /**
   * Gets or sets the username of the user.
   * @nullable
   */
  userName?: string | null;
  sortBy: ApplicationUserSortBy;
  /** Reverses the default sort behavior of the SortBy field. */
  reverseSort: boolean;
} & Required<
    Pick<
      PagedRequestDtoBase & {
        /**
         * Gets or sets the email of the user.
         * @nullable
         */
        email?: string | null;
        /**
         * Gets or sets the username of the user.
         * @nullable
         */
        userName?: string | null;
        sortBy: ApplicationUserSortBy;
        /** Reverses the default sort behavior of the SortBy field. */
        reverseSort: boolean;
      },
      "reverseSort" | "sortBy"
    >
  >;
