/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */
import type { StaticContentFormat } from "./static-content-format";

/**
 * An end-user-ready CMS item.
 */
export interface PublishedStaticContentDto {
  /** The content. */
  content: string;
  format: StaticContentFormat;
}
