/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */

/**
 * Data transfer object for requesting a password reset.
 */
export interface ResetPasswordRequestDto {
  /**
   * Gets or sets the email address of the user.
   * @minLength 0
   * @maxLength 256
   */
  email: string;
}
