/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */

/**
 * Represents a role for the Application Role.
 */
export interface RoleDto {
  /** Gets or sets the role name. */
  name: string;
  /** Gets or sets the role display name. */
  displayName: string;
  /** Gets or sets the role description. */
  description: string;
}
