/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */

/**
 * Represents a request to search claims.
 */
export interface SearchClaimsRequestDto {
  /**
   * Gets or sets the page number. Must be greater than 0.
   * @minimum 1
   * @maximum 2147483647
   */
  pageNumber: number;
  /**
   * Gets or sets the page size. Must be between 1 and 50.
   * @minimum 1
   * @maximum 50
   */
  pageSize: number;
  /**
   * Filter by exact claim type.
   * @nullable
   */
  type?: string | null;
  /**
   * Filter by claim type substring.
   * @nullable
   */
  typeContains?: string | null;
  /**
   * Filter by exact claim value.
   * @nullable
   */
  value?: string | null;
  /**
   * Filter by claim value substring.
   * @nullable
   */
  valueContains?: string | null;
}
