/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */
import type { PagedRequestDtoBase } from "./paged-request-dto-base";
import type { NotificationStatus } from "./notification-status";
import type { NotificationType } from "./notification-type";

/**
 * Data transfer object for searching notifications with pagination support.
 */
export type SearchNotificationsRequestDto = PagedRequestDtoBase & {
  /**
   * Gets or sets the ID of the notification to start the search from.
   * @nullable
   */
  sinceId?: number | null;
  /**
   * Gets or sets the ID of the notification to end the search at.
   * @nullable
   */
  priorToId?: number | null;
  status?: NotificationStatus;
  type?: NotificationType;
};
