/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */

/**
 * Represents a request to search external logins.
 */
export interface SearchExternalLoginsRequestDto {
  /**
   * Gets or sets the page number. Must be greater than 0.
   * @minimum 1
   * @maximum 2147483647
   */
  pageNumber: number;
  /**
   * Gets or sets the page size. Must be between 1 and 50.
   * @minimum 1
   * @maximum 50
   */
  pageSize: number;
  /**
   * The optional login provider to filter by.
   * @nullable
   */
  loginProvider?: string | null;
  /**
   * The optional user ID to filter by.
   * @nullable
   */
  userId?: string | null;
}
