/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */
import type { SearchClaimsRequestDto } from "./search-claims-request-dto";

/**
 * Represents a request to search user claims.
 */
export type SearchUserClaimsRequestDto = SearchClaimsRequestDto & {
  /**
   * Filter by user.
   * @nullable
   */
  userId?: string | null;
};
