/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */
import type { SearchClaimsRequestDto } from "./search-claims-request-dto";
import type { SearchUserClaimsRequestDto } from "./search-user-claims-request-dto";

/**
 * Represents a request to search claims.
 */
export type SearchClaimsBodyThree = SearchClaimsRequestDto | SearchUserClaimsRequestDto;
