/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */
import type { NotificationStatus } from "./notification-status";
import type { NotificationType } from "./notification-type";

/**
 * Data transfer object for searching notifications with pagination support.
 */
export interface SearchNotificationsRequestDto {
  /**
   * Gets or sets the page number. Must be greater than 0.
   * @minimum 1
   * @maximum 2147483647
   */
  pageNumber: number;
  /**
   * Gets or sets the page size. Must be between 1 and 50.
   * @minimum 1
   * @maximum 50
   */
  pageSize: number;
  /**
   * Gets or sets the ID of the notification to start the search from.
   * @nullable
   */
  sinceId?: number | null;
  /**
   * Gets or sets the ID of the notification to end the search at.
   * @nullable
   */
  priorToId?: number | null;
  status?: NotificationStatus;
  type?: NotificationType;
}
