/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */
import type { PagedRequestDtoBase } from "./paged-request-dto-base";

/**
 * Represents a request to search claims.
 */
export type SearchClaimsRequestDto = PagedRequestDtoBase & {
  /**
   * Filter by exact claim type.
   * @nullable
   */
  type?: string | null;
  /**
   * Filter by claim type substring.
   * @nullable
   */
  typeContains?: string | null;
  /**
   * Filter by exact claim value.
   * @nullable
   */
  value?: string | null;
  /**
   * Filter by claim value substring.
   * @nullable
   */
  valueContains?: string | null;
};
