/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */
import type { PagedRequestDtoBase } from "./paged-request-dto-base";

/**
 * Represents a request to search external logins.
 */
export type SearchExternalLoginsRequestDto = PagedRequestDtoBase & {
  /**
   * The optional login provider to filter by.
   * @nullable
   */
  loginProvider?: string | null;
  /**
   * The optional user ID to filter by.
   * @nullable
   */
  userId?: string | null;
};
