/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */
import type { PagedRequestDtoBase } from "./paged-request-dto-base";
import type { IntegrationProvider } from "./integration-provider";

/**
 * DTO for searching integrations.
 */
export type SearchIntegrationsRequestDto = PagedRequestDtoBase & {
  provider?: IntegrationProvider;
  /**
   * The user ID to filter for.
   * @nullable
   */
  userId?: string | null;
};
