/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */
import type { StaticContentReadAccess } from "./static-content-read-access";
import type { StaticContentStatus } from "./static-content-status";
import type { StaticContentType } from "./static-content-type";
import type { StaticContentSortBy } from "./static-content-sort-by";

export interface SearchStaticContentRequestDto {
  /**
   * Gets or sets the page number. Must be greater than 0.
   * @minimum 1
   * @maximum 2147483647
   */
  pageNumber: number;
  /**
   * Gets or sets the page size. Must be between 1 and 50.
   * @minimum 1
   * @maximum 50
   */
  pageSize: number;
  /**
   * Substring key search filter.
   * @nullable
   */
  keyContains?: string | null;
  readAccess?: StaticContentReadAccess;
  status?: StaticContentStatus;
  type?: StaticContentType;
  sortBy: StaticContentSortBy;
  /** Reverses the default sort behavior of the SortBy field. */
  reverseSort: boolean;
}
