/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */
import type { PagedRequestDtoBase } from "./paged-request-dto-base";
import type { StaticContentReadAccess } from "./static-content-read-access";
import type { StaticContentStatus } from "./static-content-status";
import type { StaticContentType } from "./static-content-type";
import type { StaticContentSortBy } from "./static-content-sort-by";

/**
 * Settings for a CMS search request.
 */
export type SearchStaticContentRequestDto = PagedRequestDtoBase & {
  /**
   * Substring key search filter.
   * @nullable
   */
  keyContains?: string | null;
  readAccess?: StaticContentReadAccess;
  status?: StaticContentStatus;
  type?: StaticContentType;
  sortBy: StaticContentSortBy;
  /** Reverses the default sort behavior of the SortBy field. */
  reverseSort: boolean;
} & Required<
    Pick<
      PagedRequestDtoBase & {
        /**
         * Substring key search filter.
         * @nullable
         */
        keyContains?: string | null;
        readAccess?: StaticContentReadAccess;
        status?: StaticContentStatus;
        type?: StaticContentType;
        sortBy: StaticContentSortBy;
        /** Reverses the default sort behavior of the SortBy field. */
        reverseSort: boolean;
      },
      "reverseSort" | "sortBy"
    >
  >;
