/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */
import type { PagedRequestDtoBase } from "./paged-request-dto-base";

/**
 * Represents a request to search a specific claim.
 */
export type SearchClaimRequestDto = PagedRequestDtoBase & {
  /** Filter by exact claim type. */
  type: string;
  /** Filter by exact claim value. */
  value: string;
} & Required<
    Pick<
      PagedRequestDtoBase & {
        /** Filter by exact claim type. */
        type: string;
        /** Filter by exact claim value. */
        value: string;
      },
      "type" | "value"
    >
  >;
