/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */

/**
 * Data transfer object for requesting a magic link.
 */
export interface SendMagicLinkRequestDto {
  /**
   * The email address to send the magic link to.
   * @minLength 0
   * @maxLength 256
   */
  email: string;
}
