/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */

/**
 * Data transfer object for requesting a verification email.
 */
export interface SendVerificationEmailRequestDto {
  /**
   * The email to send to.
   * @minLength 0
   * @maxLength 256
   */
  email: string;
}
