/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */

/**
 * Data transfer object for setting a user setting.
 */
export interface SetUserSettingRequestDto {
  /** The unique identifier for the user setting. */
  key: string;
  /** The value to assign to the user setting. */
  value: string;
}
