/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */

/**
 * Represents the publication status of static content.
 */
export type StaticContentStatus = (typeof StaticContentStatus)[keyof typeof StaticContentStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StaticContentStatus = {
  Draft: "Draft",
  Published: "Published",
  Archived: "Archived",
} as const;
