/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */

/**
 * Defines a supported language for static content.
 */
export interface StaticContentSupportedLanguageDto {
  /** The language shortcode, such as "en". */
  languageCode: string;
  /** The full name of the language, such as "English". */
  languageName: string;
}
