/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */

/**
 * The type of CMS item.
 */
export type StaticContentType = (typeof StaticContentType)[keyof typeof StaticContentType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StaticContentType = {
  Zone: "Zone",
  Page: "Page",
} as const;
