/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */

/**
 * The read access of a CMS item.
 */
export type StaticContentReadAccess = (typeof StaticContentReadAccess)[keyof typeof StaticContentReadAccess];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StaticContentReadAccess = {
  Public: "Public",
  Authenticated: "Authenticated",
  Explicit: "Explicit",
} as const;
