/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */

/**
 * Supported static content sorting options.
 */
export type StaticContentSortBy = (typeof StaticContentSortBy)[keyof typeof StaticContentSortBy];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StaticContentSortBy = {
  Key: "Key",
  Status: "Status",
  Type: "Type",
  ReadAccess: "ReadAccess",
  CreatedDate: "CreatedDate",
  LastModifiedDate: "LastModifiedDate",
} as const;
