/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */

/**
 * Supported CMS content formats.
 */
export type StaticContentFormat = (typeof StaticContentFormat)[keyof typeof StaticContentFormat];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StaticContentFormat = {
  Html: "Html",
  Markdown: "Markdown",
  PlainText: "PlainText",
} as const;
