/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */
import type { StaticContentType } from "./static-content-type";
import type { StaticContentStatus } from "./static-content-status";
import type { StaticContentReadAccess } from "./static-content-read-access";

/**
 * Data transfer object for static content response.
Contains metadata and audit information about static content items.
 */
export interface StaticContentDto {
  /** Gets or sets the unique identifier for the static content. */
  id: number;
  type: StaticContentType;
  /** Gets or sets the unique key identifier for the static content. */
  key: string;
  status: StaticContentStatus;
  readAccess: StaticContentReadAccess;
  /**
   * Gets or sets the comma-separated list of roles that can edit this content.
   * @nullable
   */
  editorRoles?: string | null;
  /**
   * Gets or sets the comma-separated list of roles that can read this content.
   * @nullable
   */
  readerRoles?: string | null;
  /** Gets or sets the date and time when the content was created. */
  createdDate: string;
  /**
   * Gets or sets the user identifier who created this content.
   * @nullable
   */
  createdByUserId: string | null;
  /**
   * Gets or sets the date and time when the status was last changed.
   * @nullable
   */
  statusChangedDate: string | null;
  /**
   * Gets or sets the user identifier who last changed the status.
   * @nullable
   */
  statusChangedByUserId: string | null;
  /**
   * Gets or sets the date and time when the content was last modified.
   * @nullable
   */
  lastModifiedDate: string | null;
  /**
   * Gets or sets the user identifier who last modified this content.
   * @nullable
   */
  lastModifiedByUserId: string | null;
}
