/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */

/**
 * Describes the visibility level of static content to the current user.
 */
export type StaticContentUserVisibility = (typeof StaticContentUserVisibility)[keyof typeof StaticContentUserVisibility];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StaticContentUserVisibility = {
  RequiresAuthentication: "RequiresAuthentication",
  Restricted: "Restricted",
  Reader: "Reader",
  Editor: "Editor",
} as const;
