/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */
import type { ApiResponseType } from "./api-response-type";

/**
 * Represents the response of an API call.
 */
export interface StringApiResponseDto {
  /**
   * Gets or sets the result of the API call.
   * @nullable
   */
  result?: string | null;
  type: ApiResponseType;
  /**
   * Gets or sets the error messages associated with the API response.
   * @nullable
   */
  errorMessages?: string[] | null;
}
