/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */

/**
 * Represents a paginated response.
 */
export interface StringPagedResponseDto {
  /** Gets or sets the data for the current page. */
  data: string[];
  /** Gets or sets the current page number. */
  pageNumber: number;
  /** Gets or sets the size of the page. */
  pageSize: number;
  /** Gets or sets the total count of items. */
  totalCount: number;
  /** Gets the total number of pages. */
  readonly totalPages: number;
}
