/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */
import type { IntegrationProviderDefinition } from "./integration-provider-definition";
import type { IntegrationCategoryDefinition } from "./integration-category-definition";
import type { IntegrationFeatureDefinition } from "./integration-feature-definition";

/**
 * DTO for supported integrations.
 */
export interface SupportedIntegrationsDto {
  /** The supported integration providers. */
  providers: IntegrationProviderDefinition[];
  /** The supported integration categories. */
  categories: IntegrationCategoryDefinition[];
  /** The supported integration features. */
  features: IntegrationFeatureDefinition[];
}
