/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */

/**
 * Represents an external authentication provider supported by the application, including its identifier and
display name.
 */
export interface SupportedExternalLoginDto {
  /** The unique name or identifier of the external authentication provider (for example, "Google" or "Facebook").
            Cannot be null or empty. */
  providerName: string;
  /** The user-friendly name of the external authentication provider as displayed in the UI. Cannot be null or empty. */
  displayName: string;
  /** Gets the full path URL for initiating an external login with the specified provider. */
  readonly loginUrl: string;
}
