/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */
import type { StaticContentType } from "./static-content-type";
import type { StaticContentStatus } from "./static-content-status";
import type { StaticContentReadAccess } from "./static-content-read-access";

/**
 * Data transfer object for updating static content.
 */
export interface UpdateStaticContentDto {
  /**
   * Gets or sets the unique identifier for the static content.
Must be in kebab-case (lowercase alphanumeric with hyphens).
   * @minLength 1
   * @maxLength 64
   * @pattern ^[a-z0-9]+(-[a-z0-9]+)*$
   */
  key: string;
  type: StaticContentType;
  status: StaticContentStatus;
  readAccess: StaticContentReadAccess;
  /**
   * Gets or sets the comma-separated list of role names that can edit this content.
Role names must be alphanumeric with hyphens and underscores only.
   * @maxLength 256
   * @nullable
   * @pattern ^[a-zA-Z0-9_-]+(,[a-zA-Z0-9_-]+)*$
   */
  editorRoles?: string | null;
  /**
   * Gets or sets the comma-separated list of role names that can view this content.
Role names must be alphanumeric with hyphens and underscores only.
   * @maxLength 256
   * @nullable
   * @pattern ^[a-zA-Z0-9_-]+(,[a-zA-Z0-9_-]+)*$
   */
  readerRoles?: string | null;
}
