/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */
import type { IntegrationDto } from "./integration-dto";
import type { AdminIntegrationDto } from "./admin-integration-dto";

/**
 * Gets or sets the result of the API call.
 * @nullable
 */
export type UpdateMyIntegration200One = IntegrationDto | AdminIntegrationDto | null;
