/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */
import type { UpdateStaticContentLanguageDto } from "./update-static-content-language-dto";
import type { CreateStaticContentLanguageDto } from "./create-static-content-language-dto";

/**
 * Specifies the settings to update the exiting language content of a CMS item with.
 */
export type UpdateStaticContentLanguageBodyOne = UpdateStaticContentLanguageDto | CreateStaticContentLanguageDto;
