/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */

/**
 * DTO for updating an integration.
 */
export interface UpdateIntegrationRequestDto {
  /**
   * The friendly name to display for this integration.
   * @maxLength 64
   */
  friendlyName: string;
  /** True if the credentials should be returned wth future client API requests. */
  shareWithClient: boolean;
  /**
   * The credentials to use for API requests.
   * @nullable
   */
  credentials?: string | null;
}
