/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */
import type { StaticContentFormat } from "./static-content-format";

/**
 * Specifies the settings to update the exiting language content of a CMS item with.
 */
export interface UpdateStaticContentLanguageDto {
  /** The content. */
  content: string;
  format: StaticContentFormat;
}
