/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */
import type { UpdateIntegrationRequestDto } from "./update-integration-request-dto";
import type { CreateIntegrationRequestDto } from "./create-integration-request-dto";

/**
 * DTO for updating an integration.
 */
export type UpdateMyIntegrationBodyOne = UpdateIntegrationRequestDto | CreateIntegrationRequestDto;
