/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */

/**
 * The data transfer object for updating a profile. Update fields here when editable profile fields change.
 */
export interface UpdateProfileRequestDto {
  [key: string]: unknown;
}
