/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */
import type { UpdateStaticContentDto } from "./update-static-content-dto";
import type { CreateStaticContentDto } from "./create-static-content-dto";

/**
 * Data transfer object for updating static content.
 */
export type UpdateStaticContentBodyTwo = UpdateStaticContentDto | CreateStaticContentDto;
