/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */

/**
 * Data transfer object for user claims, extending base claim information with user identification.
 */
export interface UserClaimDto {
  /** Gets or sets the claim type. */
  type: string;
  /** Gets or sets the claim value. */
  value: string;
  /** Gets or sets the unique identifier of the user associated with this claim. */
  userId: string;
}
