/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */
import type { ClaimDto } from "./claim-dto";

/**
 * Data transfer object for user claims, extending base claim information with user identification.
 */
export type UserClaimDto = ClaimDto & {
  /** Gets or sets the unique identifier of the user associated with this claim. */
  userId: string;
} & Required<
    Pick<
      ClaimDto & {
        /** Gets or sets the unique identifier of the user associated with this claim. */
        userId: string;
      },
      "userId"
    >
  >;
