/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */

/**
 * Data transfer object for user settings.
 */
export interface UserSettingDto {
  /** Gets or sets the unique identifier key for the setting. */
  key: string;
  /** Gets or sets the value associated with the setting key. */
  value: string;
  /**
   * Gets or sets the date and time when the setting was created.
   * @nullable
   */
  createdDate?: string | null;
  /**
   * Gets or sets the date and time when the setting was last modified.
   * @nullable
   */
  lastModifiedDate?: string | null;
}
