/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */

/**
 * Data transfer object for submitting an email verficiation code.
 */
export interface VerifyEmailRequestDto {
  /**
   * The email.
   * @minLength 0
   * @maxLength 256
   */
  email: string;
  /**
   * The verification code.
   * @minLength 0
   * @maxLength 512
   */
  code: string;
}
