/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LightNap.WebApi
 * OpenAPI spec version: 1.0
 */

/**
 * Data transfer object for verifying a 2FA code.
 */
export interface VerifyCodeRequestDto {
  /**
   * The email address or user name of the user.
   * @minLength 0
   * @maxLength 256
   */
  login: string;
  /**
   * The verification code.
   * @minLength 0
   * @maxLength 512
   */
  code: string;
  /** True to remember the user on this device. */
  rememberMe: boolean;
  /**
   * The details of the device.
   * @minLength 0
   * @maxLength 512
   */
  deviceDetails: string;
}
